### ISSUE TITLE
Any plans for releasing images for Windows Containers ??

### ISSUE THREAD

**Issue by harshil93** [microsoft/vsts-agent-docker#1]
Since Windows Server 2016 is out, are there any plans for releasing images for Windows Containers ?

**Comment by DjTrilogic** [comment]
+1

**Comment by stepro** [comment]
It's a reasonable assumption to make that these would exist. @chrisrpatterson, what do you think?

**Comment by chrisrpatterson** [comment]
We would like to, however, in my experiments I have had a difficult time getting most of the toolsets that one would expect to work on Windows working in a container.  We could get one working with a similar set of tooling that we are offering in the Linux containers, however, I don't think  you would have the full feature of VS there yet.

**Comment by rs38** [comment]
Checked https://github.com/Microsoft/vsts-agent-docker/tree/windows/windows ?

**Comment by artisticcheese** [comment]
Anybody could comment if they were successful running Windows container image?

**Comment by xtophs** [comment]
I've been able to build and run a Windows Container with the VSTS agent from this repo. Unfortunately, you can't run the container to execute Windows Container builds because that would require running Docker inside the Windows Container that's running the agent. If you're looking to build windows containers, you have to run the agent on a WS2016 VM.

**Comment by xtophs** [comment]
I published a little write up on building Windows Containers here: 

https://github.com/xtophs/vsts-building-windows-server-containers

**Comment by DenisBiondic** [comment]
Isn't this stating that docker is possible to run under nano / windows server core:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/deploy-containers-on-server
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/deploy-containers-on-nano

or am I completely not understanding the issue above? We are takling about executing "docker build" from a windows base image on a windows container, right?

**Comment by rs38** [comment]
the initial issue/question is, if there is an docker image (pref. on Docker Hub) that has bundled ( a.k.a docker build) a working vsts agent on either nano or core.

**Comment by jwittner** [comment]
Would really love if the base windows ones were available as tagged versions here: https://store.docker.com/community/images/microsoft/vsts-agent

**Comment by ljt91** [comment]
+1 - Would love to have Windows images.

**Comment by mot256** [comment]
+1000000
Any progress on this?

**Comment by s3raph** [comment]
This would be incredibly useful. I see that there's an image and a set of scripts available.

I see that there's one available on master. Is it close to being released?

**Comment by Rabadash8820** [comment]
Ok seriously, what is the hold-up here?  I asked about creating a Windows VSTS agent image over on [StackOverflow](https://stackoverflow.com/questions/48891357/docker-for-windows-dockerfile) was redirected to this repo, and was able to build/run the Dockerfile in this repo without issue.  If I can do it, why can't Microsoft publish it on the Docker Store and make it official?  Right now it just feels like you guys aren't supporting your own operating system!

**Comment by cocowalla** [comment]
Almost another half year has passed, so I figure this is worth a bump. @stepro, is there any chance of getting a Windows VSTS agent published to Docker Hub?

I need the full .NET Framework (amongst other Windows-only things), so a supported, pre-built Windows image would be great.

**Comment by olljanat** [comment]
@stepro if I create template for this can we then get VSTS agent for Windows published to Docker HUB?

As Windows Server 2019 is already released and it also supports mounting Docker named pipe ( npipe:////./pipe/docker_engine ) inside of container I think that it is good idea to only support it for now.

It is easiest to start from *docker* image which would contain:
* LTSC version of OS: *mcr.microsoft.com/windows/servercore:ltsc2019*
* Docker 18.09.1 client
* VSTS agent

so target for it would be *microsoft/vsts-agent:windowsservercore-ltsc2019-docker-18.09.1*
