### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by enricforn** [Microsoft/vsts-agent-docker#10]
We just install TFS2017 on premise version 15.105.25910.0.

I'm trying to run an agent to a container by running the following command:

docker run -e TFS_HOST=tfs.mycompany.com -e TFS_URL=https://tfs.mycompany.com -e VSTS_TOKEN=************************** -e VSTS_AGENT=%hostname% -e VSTS_WORK=_work -e VSTS_POOL=docker -it microsoft/vsts-agent:ubuntu-16.04-tfs-2017

And I'm getting this output:

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html

>> Connect:

Invalid configuration provided for username. Terminating unattended configuration.

I tried also running an agent from a container with an account created on VS online, and it works fine:

docker run -e VSTS_ACCOUNT=enformat -e VSTS_TOKEN=***************************** -e VSTS_POOL=docker -it microsoft/vsts-agent:ubuntu-16.04

Is there any problem with start.sh script ?

Do we need to configure custom authentication on our servers (anonymous authentication is enabled) ? Right now we've got agents installed on premise and they are working fine.

**Comment by stepro** [comment]
Thanks for reporting the issue. @chrisrpatterson, I was never able to get a TFS on-prem instance up and running so I couldn't validate that the changes to support TFS were going to work. Can you help @enricforn?

**Comment by stepro** [comment]
@enricforn, can you describe how you are currently installing and starting agents that successfully connect to your on-prem instance? I assume the image's startup script is incorrect for the on-prem case but since I don't have an on-prem server to test against, I don't know where the issue is. Thanks!

**Comment by enricforn** [comment]
@stepro I'm using negotiate authentication to configure the agent, and is working fine. If you think is interesting, I can create a pull request by adding this feature to the project. PAT authentication seems is not working properly. However, I tried with VSTS and is working fine.

**Comment by stepro** [comment]
I'd love to see a PR that shows how the startup.sh script needs to be fixed, since I'm in the dark without an on-prem server to test against. Thanks!

**Comment by stffabi** [comment]
Adding `--auth` and the token seemed to fix the problem for us.
```
./bin/Agent.Listener configure --unattended \
  --agent "${VSTS_AGENT:-$(hostname)}" \
  --url "$TFS_URL" \
  --auth PAT \
  --token "$VSTS_TOKEN" \
  --pool "${VSTS_POOL:-Default}" \
  --work "${VSTS_WORK:-_work}" \
  --replace & wait $!
```

**Comment by stffabi** [comment]
I've opened a PR for this.

**Comment by mmisztal1980** [comment]
I've just run into this while running my containers with:

`docker run -d --name  build-agent_1 -e TFS_HOST=$TFS_HOST -e VSTS_TOKEN=*** -e VSTS_POOL=$POOL -v /home/tfsservice/agent/microsoft/vsts-agent_1:/vsts/agent/_work -v /var/run/docker.sock:/var/run/docker.sock microsoft/vsts-agent:ubuntu-16.04-tfs-2018-u3-doc
ker-18.06.1-ce`

I keep getting a:

```
>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html


>> Connect:
```

None of my dockerized agents connect to our TFS.

Is there something I'm missing?

**Comment by enricforn** [comment]
@mmisztal1980 I've created a new agent by adding a new credential configuration. You can check it out at https://github.com/enricforn/vsts-agent-docker

**Comment by mmisztal1980** [comment]
just found what the issue was, I was supplying `https://tfs.mydomain.com/tfs` to the agents instead of `tfs.mydomain.com`
