### ISSUE TITLE
Enable IPv6

### ISSUE THREAD

**Issue by zooba** [microsoft/vsts-agent-docker#101]
IPv6 appears to be disabled in the containers. Can it be enabled? (Appears to be off by default in Docker, but [easy to enable](https://docs.docker.com/config/daemon/ipv6/))

**Comment by zooba** [comment]
The context is that we have builds/tests running for [CPython](https://python.visualstudio.com/cpython) (it's public) that validate IPv6 behaviour. Some have been failing because we weren't correctly handling when it's disabled, and while we've fixed those, it would also be nice for those tests to run correctly.

As far as I understand, we don't need internet access - just the ability to bind to `::1`.

**Comment by stepro** [comment]
If this is purely an issue with how Docker is running, I assume you are asking about the hosted Linux build agents? This repository provides self-host images for running VSTS agents, and in that case you own your own Docker daemon, so feel free to enable IPv6. If you discover there's something specific that needs to be done in the VSTS agent images here, please let me know.

**Comment by zooba** [comment]
Yeah, sorry, missed that bit of info :)

Unfortunately, switching to our own hosting means we can't take advantage of the hosted machines we've been donated already. Is there some reason the hosted ones can't/shouldn't enable IPv6?

**Comment by stepro** [comment]
@chrisrpatterson or @thechrisjohnson are best set up to answer that question.
