### ISSUE TITLE
Build YAML definitions permissions

### ISSUE THREAD

**Issue by mswehli** [Microsoft/vsts-agent-docker#114]
Can you let me know if it might be possible to set permissions for who can trigger the creation of a build definition by adding a .vsts-ci.yml file when Build YAML definitions is turned on in the preview features panel.

**Comment by DavidStaheli** [comment]
Hi @mswehli, can you please post this question on the following GitHub repo?  That should get the right eyes on your question.  Thanks!
https://github.com/Microsoft/vsts-agent
