### ISSUE TITLE
Default PHP version (7.2) missing extensions required for composer

### ISSUE THREAD

**Issue by madhancock** [Microsoft/vsts-agent-docker#115]
PHP set up in #108 default the installed version of PHP to 7.2.

When composer is run on packages requiring ext-curl an error is thrown and builds fail.

Ouputs for `php -m`:

```
[PHP Modules]
amqp
apcu
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
json
libxml
memcache
memcached
mongodb
msgpack
openssl
pcntl
pcre
PDO
Phar
posix
readline
redis
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
yaml
Zend OPcache
zlib
zmq

[Zend Modules]
Xdebug
Zend OPcache
```

Outputs for `php7.1 -m`:

```
[PHP Modules]
amqp
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mcrypt
memcache
memcached
mongodb
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib
zmq

[Zend Modules]
Xdebug
Zend OPcache
```

This issue affects all versions of PHP bundled with the image. The required extensions need to be installed on every included version.

Currently the only workaround is to force the agent to default to PHP 7.1 by either running the composer command with full paths or running `update-alternatives --set php /usr/bin/php7.1` in a shell before running any composer commands.

**Comment by dakale** [comment]
New images have been pushed. Let me know if you are not seeing this fixed in latest images.
