### ISSUE TITLE
Install Build Tools 2017

### ISSUE THREAD

**Issue by heaths** [microsoft/vsts-agent-docker#116]
Visual Studio in a container is not only much bigger than necessary (installs UI components when Windows containers do not support UI and no plans to currently), it's also not officially supported.

Please install the Build Tools SKU instead, as documented at https://docs.microsoft.com/visualstudio/install/build-tools-container (there's also a more advanced topic available underneath that which may be more accommodating).

**Comment by kirkone** [comment]
Hi,

I am about to get this working in #91 
any help would be nice.

CU
KirK
