### ISSUE TITLE
Add Chrome web browser to Hosted Linux agent

### ISSUE THREAD

**Issue by stewx** [Microsoft/vsts-agent-docker#122]
We would like to have Chrome available for running web app unit tests on the Linux hosted agents. It is available on the Hosted VS2017 agents and works great on there:
https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

**Comment by dakale** [comment]
I added the `google-chrome` package: https://github.com/Microsoft/vsts-agent-docker/commit/cf55875fb42b55a0f68419df844b2d90d4d40e19

Ill close this when it is deployed to hosted pools, but the updated images are pushed and you can try them out if you run it as a private agent

**Comment by dakale** [comment]
Actually, since this related to Hosted Pools, please track the progress here: https://github.com/Microsoft/vsts-image-generation/issues/181

From the Docker image perspective, this is complete.

**Comment by stewx** [comment]
Can you confirm if CHROME_BIN gets set as part of the installation?
