### ISSUE TITLE
conda: command not found

### ISSUE THREAD

**Issue by dparkar** [Microsoft/vsts-agent-docker#127]
Tested with two images tagged "ubuntu-16.04-standard" and "latest", conda doesn't seem to be in PATH.
![image](https://user-images.githubusercontent.com/208161/43681325-c6932964-9804-11e8-82b3-a923e60a4ee6.png)

**Comment by dakale** [comment]
Please see https://github.com/Microsoft/vsts-agent-docker/pull/128 for justification of why this doesnt work well within the context of existing image functionality
