### ISSUE TITLE
links to dockerfiles are stale

### ISSUE THREAD

**Issue by dwj300** [Microsoft/vsts-agent-docker#134]
example: https://github.com/microsoft/vsts-agent-docker/blob/cf55875fb42b55a0f68419df844b2d90d4d40e19/ubuntu/14.04/Dockerfile

should be master branch not the specific blob

**Comment by dakale** [comment]
The links are intentionally to a blob. It represents the exact Dockerfile that was used to generate whatever image is currently pushed to the repository. Theres definitely tradeoffs to either approach but its not something I plan to change without overhauling the entire README. You can still browse those links to find paths to relevant Dockerfiles, even if it doesnt take you directly to the file on master, but it allows you to inspect what exact Dockerfile generated the image you pulled, should there be any issues etc
