### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by MadsBogeskov** [Microsoft/vsts-agent-docker#137]
TFS Version: 16.122.27409.2

I am trying to create a docker image for a build agent for my organization. 

The Dockerfile I have created is looking like this:
```
FROM microsoft/vsts-agent:ubuntu-16.04-tfs-2018-u1

ENV TFS_HOST <HOST>
ENV VSTS_TOKEN <PAT>
ENV VSTS_POOL <POOL>
ENV VSTS_AGENT Docker-Agent-$(hostname)
```

However when I run the docker container I keep getting this:
```
>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html


>> Connect:

Connecting to server ...
An error occurred while sending the request.
```

Is there anyway to get more verbose information about what went wrong?

**Comment by MadsBogeskov** [comment]
For following up on this. A way to debug this scenario is to run `docker cp <container_instance_id>:/vsts .` which will copy the vsts directory from the crashed container into the same directory. In there you can see the _diag directory with the log file. 

The problem in this case seems to be that the TFS server doesn't have a valid SSL certificate.

**Comment by dakale** [comment]
Thanks for following up with this, I think it will be useful for others. Copying logs out is definitely a better solution than committing the crashed container and shelling into it. There may be a way to redirect the agents logs to stdout so it will show in the docker logs, ill look into that as well and drop an update here if I find out.

Marking this as resolved for now
