### ISSUE TITLE
Add a GitHub Release/Tag for each new version

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/vsts-agent-docker#139]
Hi there, is it possible/relevant to add a new GitHub Release/Tag for each new version/image of the VSTS-Agent-Docker? I know there is already the Docker image tag itself in DockerHub, but was just wondering if you could also add this part in GitHub. Thanks!

**Comment by dakale** [comment]
This is a good idea for something we may consider in the future, but I would want to have some more automation around building in place first. Not interested in manually updating releases when I build these images. 

Will leave open for now and revisit when it makes sense
