### ISSUE TITLE
Building Windows image hangs after installing choco packages

### ISSUE THREAD

**Issue by jmezach** [microsoft/vsts-agent-docker#14]
I noticed that a version for Windows has landed in this repo, so I tried to built it myself. However, building the standard image seems to hang after first wave of Chocolatey packages have been installed. Is that a known issue? Anything I can help with? Would love to give this a try.

**Comment by artisticcheese** [comment]
What docker log shows?

**Comment by jmezach** [comment]
After aborting docker build and retrying it a couple of times I've now build an image successfully. Haven't tried to run it yet though ;).

**Comment by chrisrpatterson** [comment]
From what I have seen it does not exactly hang but takes a very long time to commit due to Antimalware running.
