### ISSUE TITLE
Remove requirement for PAT when container restarts

### ISSUE THREAD

**Issue by alexvy86** [Microsoft/vsts-agent-docker#141]
I'm having a hard time figuring out what should be the expected behavior of a container running the VSTS agent, when it restarts. I recently had to reboot the host where the container had been running for a couple of months without issues, and when trying to restart the container once the machine came back up, I got errors complaining about the PAT (the one I used when first starting the container had already expired). I ended up scraping it up and creating a brand new container with a brand new PAT.

I looked at the Dockerfile and it seems that [VSTS_TOKEN or VSTS_TOKEN_FILE do need to be set every time the container runs](https://github.com/Microsoft/vsts-agent-docker/blob/ac531c7aaf947972910fce3b43a218cd53aa5714/ubuntu/16.04/start.sh#L64). So, since the longest a PAT can be set to be valid is 1 year, is it expected that (in the worst case) after that time, the container with the VSTS Agent will have to be replaced entirely, or a new PAT provided to it through a mounted file? Would it be possible (maybe with an environment variable, e.g. SKIP_AGENT_UPDATE_ERRORS) to make it so the container ignores this error and tries to run the agent if it's already installed?

**Comment by alexvy86** [comment]
Well, it is documented [here](https://docs.microsoft.com/en-us/vsts/pipelines/agents/agents?view=vsts#personal-access-token-pat) that for a VSTS agent installed directly on a server, the PAT is only needed once when registering the agent, and never again. So using short-lived PATs in that scenario is fine. But for containerized agents, it seems that the PAT is required forever, if we expect the containers to be able to restart successfully? And restarts *will* happen, at the very least for planned maintenance of the host.

The issues to me are two:
- The disconnect regarding PAT requirements for containerized VSTS agents and non-containerized ones, and the lack of documentation on the former if the disconnect is inevitable.
- The fact that this implies that we need to use long-lived PATs for containerized agents, and that even then, they have a "shelf-life" of 1 year because that's the max expiration time for a PAT. And if I understood you correctly, once the PAT expires there's no alternative but to scrap that container and create a new one...?

What I'd like to see are containerized agents that only need a PAT at registration time, and then can restart without issues even if the PAT expired. I understand that this poses an issue for the piece of the script that checks for updates, and I don't have a clear solution for that in my head, but at least I hope I explained better what I think the problem is.

If it's not possible to align the PAT requirements for containerized and non-containerized agents, then at least it'd be nice to have clearer documentation on what containerized agents need. If that's the way this has to go, I can take a shot at a PR with that.

**Comment by alexvy86** [comment]
I get the gist of the workarounds you propose and I need to think a bit more about them as well. But one thing that stood out, in my mind I wouldn't be recreating the container from scratch when the host reboots, just starting the same one (which stopped due to the host reboot, but still exists). And AFAIK, stopping and starting a container doesn't wipe out its filesystem (like removing the container and starting a new one would)...? So I was thinking that if the startup script could somehow check for "have I configured the agent in this container already" (maybe using one of your ideas above), and skip the parts that require the PAT if it has, that would solve the issue? When starting a brand new container, nothing has been configured, the PAT needs to be passed in in environment variables, and everything happens exactly as it does right now. Then if the container stops and starts, the script would (somehow) detect that the agent is already configured and just start it.

I'll give this more thought later today and see if I can come up with anything else.

And just to be on the same page, in the scenario of removing the container and creating a brand new one, I totally agree that it needs to go through the initial setup (including downloading the agent) and that should require the PAT.

**Comment by dakale** [comment]
Okay, Ill have to test that and report back. I would assume based on the snippet I pasted above from the start script, that it would just start the agent if the config files were present, but maybe that is not working as expected. Ill report back

**Comment by dakale** [comment]
It seems like the problem is when the cleanup function is executed upon the container being stopped (from start.sh):
```bash
cleanup() {
  if [ -e config.sh ]; then
    ./bin/Agent.Listener remove --unattended \
      --auth PAT \
      --token $(cat "$VSTS_TOKEN_FILE")
  fi
}
```
to remove the agent from the server, also removes the credentials from disk for security, see agent logs:
```
2018-09-05 14:55:29Z: Listening for Jobs
^C
Exiting...
Removing agent from the server
Connecting to server ...
Succeeded: Removing agent from the server
Removing .credentials
Succeeded: Removing .credentials
Removing .agent
Succeeded: Removing .agent
```

I tried killing the container directly to circumvent this cleanup during SIGINT/SIGTERM but the server will not allow a new agent to reconnect with the same credentials, because a session already exists

I committed the running container, killed and reran it, see logs:
```
$ docker run -it test/stopped3 bash
root@54c8df8ae266:/vsts# agent/bin/Agent.Listener
Scanning for tool capabilities.
Connecting to the server.
A session for this agent already exists.
2018-09-05 14:49:17Z: Agent connect error: The task agent 61ae44d1de95 already has an active session for owner 61ae44d1de95.. Retrying until reconnected.
A session for this agent already exists.
^CExiting...
```

So I dont think this is something we can support in these Docker images, it would require vsts-agent functionality, or maybe theres a flag on the agent I dont know about. Feel free to open an issue in vsts-agent, but Im not sure if cleanup without removing credentials is something they will want to support

**Comment by ljani** [comment]
The normal agent supports recovering the connection without a PAT after a reboot, right? Why we cannot do the same with the docker image, just use a persistent volume to store whatever info is needed?

**Comment by ljani** [comment]
Why we cannot use persistent volumes of Docker to store the same information as the agent normally does to survive reboots and crashes? Ie.

1. Run agent once (with interactive tty?) to configure it and store the configuration and the token to a persistent volume
2. Now one can restart the configured agent without a PAT

The VSTS agent already stores this information somewhere, so I don't think that's not a problem. We just need to lookup where.
