### ISSUE TITLE
linux hosted tool cache and disk usage

### ISSUE THREAD

**Issue by jordimontana82** [Microsoft/vsts-agent-docker#144]
Hi!

Firs of all, thx a mill for setting up these docker files, they're amazing.

This is more of a question really, as I was setting up a custom vsts docker image based on the standard one, and was wondering, what does the [hosted tool cache contains?](https://github.com/microsoft/vsts-agent-docker/blob/3049d0142e09ba09ff090e9d763f8eadedab89de/ubuntu/16.04/standard/Dockerfile#L544-L545)? As it is creating a pretty big image size (6 GB?)

**Comment by dakale** [comment]
The hosted tools cache is a few (maybe ~4) versions of python and ruby. They are used in ~VSTS~ Azure Pipelines to quickly select which version of the tool you want to put on the PATH for the context of the build. 

If you are extending the images, please consider using just the vsts-agent:ubuntu-16.04, or 14. You probably dont need standard. All that does is pull in a universe of different tools to support many types of builds. The vsts-agent:ubuntu-16.04 will carry the agent, and then you can just install the software you need for your builds. And if you arent using "Use Python version" or "Use Ruby version" tasks in your build, you wont need the hosted tools cache anyway. 

Let me know if you have any more questions

**Comment by jordimontana82** [comment]
Great, thx for your quick reply!
