### ISSUE TITLE
 Service Fabric CI/CD support for Linux Azure DevOps Agent pools

### ISSUE THREAD

**Issue by MedAnd** [microsoft/vsts-agent-docker#145]
Currently the [Microsoft-hosted Linux pools](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml) do not have the Service Fabric SDK installed. Since the Linux agent pools [run on an Ubuntu Linux host inside the vsts-agent-docker container](https://github.com/Microsoft/vsts-agent-docker), consider adding support for the Service Fabric SDK. This will enable rapid CI/CD for Linux Service Fabric projects in Azure DevOps.

![image](https://user-images.githubusercontent.com/13365135/45429002-baa5e380-b6e5-11e8-83d5-b56dd44991d4.png)

An initial workaround might be to use [Container jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml) and the [service-fabric-onebox](https://hub.docker.com/r/microsoft/service-fabric-onebox/) container?

Also posted in: https://github.com/Azure/service-fabric-issues/issues/1275

**Comment by MedAnd** [comment]
Hi @shashban, any update on this? Thx.

**Comment by MikkelHegn** [comment]
@pulkitaggarwl @bishal-pdMSFT

The main thing is being able to deploy to a cluster endpoint. Bringin SFCTL in to the container would be one option. Having a taks around SFCTL for deploying would be the better option.

**Comment by MedAnd** [comment]
@MikkelHegn - for a .Net Core Linux Service Fabric project wondering which template should be used:

![image](https://user-images.githubusercontent.com/13365135/47160052-d5015b80-d33a-11e8-95fa-283908e3ed5c.png)

**Comment by MedAnd** [comment]
@MikkelHegn - I think developers would still prefer 1st class support for Service Fabric Linux projects in the form of above Azure DevOps templates, and also ability to deploy to a target SF cluster from the Linux VSTS agent (unless this is contrary to other plans)?

**Comment by bishal-pdMSFT** [comment]
@pulkitaggarwl can you please follow up on this?

**Comment by MedAnd** [comment]
@bishal-pdMSFT @pulkitaggarwl - any update.. thx?

**Comment by pulkitaggarwl** [comment]
Thanks  a lot @MedAnd  for following up and I acknowledge the request. 

We have added this to our backlog and will try to deliver on this  as early as possible. 
 In the meanwhile, it will really help if you introduce this request to our [user voice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services?category_id=145269).  
Similar feedback from community will help us provide a more comprehensive solution.

Regards
Pulkit

**Comment by MedAnd** [comment]
@pulkitaggarwl https://developercommunity.visualstudio.com/idea/385310/service-fabric-cicd-support-for-linux-azure-devops.html

**Comment by bishal-pdMSFT** [comment]
Just bringing Service fabric SDK to Ubuntu agent will not be sufficient to deploy to cluster. The current Service fabric deploy tasks are designed to work on windows agent only and with windows SF SDK.

What we need is to either have:
1. sfctl installed on agent and then possibly having a separate sfctl based deploy/script task to deploy to cluster
2. or use HTTP client based deploy task which makes use of http client to deploy to cluster.

We are evaluating these options currently.

**Comment by MedAnd** [comment]
@bishal-pdMSFT - appreciate the update however I thought sfctl is part of the Service Fabric SDK for Linux? 

On my local Linux development VM I cannot remember installing it separately but hoping @MikkelHegn can confirm.

**Comment by MikkelHegn** [comment]
What @bishal-pdMSFT says :-) Bringing sfctl alone is only half the way, there are no OOB task supporting using sfctl.

**Comment by MedAnd** [comment]
@MikkelHegn - when you say there are no OOB tasks you mean Service Fabric steps in Azure DevOps supporting sfctl? 

Discussed in other threads but having a consistent, cross platform Service Fabric workflow using PowerShell Core would be the best option... any progress in this direction you can share @MikkelHegn  ☺️

**Comment by MikkelHegn** [comment]
Yes that is what I'm referring to.
For the second question, we have released the HTTP based core modules in preview: https://www.powershellgallery.com/packages/Microsoft.ServiceFabric.Powershell.Http/1.0.3-preview1 source: https://github.com/Microsoft/service-fabric-client-dotnet
