### ISSUE TITLE
Pipeline running container fails to initialize if user doesn't have access to usradd

### ISSUE THREAD

**Issue by cdietschrun** [Microsoft/vsts-agent-docker#147]
Trying to run our build pipeline through a container which in one of it's last steps in its Dockerfile does

`USER not_root`

This eventually leads to this error in the ADO log

`2018-10-03T15:39:31.2416691Z ##[command]/usr/bin/docker exec  30787dcf0f953ac090473db3f46e2930fa4f9e4f8658596d454dd5ed4f1734be bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
2018-10-03T15:39:31.5814245Z ##[command]/usr/bin/docker exec  30787dcf0f953ac090473db3f46e2930fa4f9e4f8658596d454dd5ed4f1734be useradd -m -u 1001 vsts_VSTSContainer
2018-10-03T15:39:31.7879524Z OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "permission denied": unknown`

Reproducing locally I was able to see the issue:

`
[not_root@69b9bd29b979 ~]$ bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
[not_root@69b9bd29b979 ~]$ useradd -m -u 1001 vsts_VSTSContainer
bash: /usr/sbin/useradd: Permission denied
[not_root@69b9bd29b979 ~]$ ll /usr/sbin/useradd
-rwxr-x--- 1 root root 118192 Nov  5  2016 /usr/sbin/useradd
`

It would be nice if this was more visible from the logs, or the documentation to say that a USER in the Dockerfile being run needs to have access to a list of commands including this one.

**Comment by dakale** [comment]
This is general feedback about the broader run-in-a-container feature. This repo is specifically for building Docker images containing the agent. Ill forward this to the correct place

**Comment by chrisrpatterson** [comment]
@cdietschrun you can add an options key to the container resource with additional command line arguments  that are passed to the docker run command.  Adding -u 0 will make the container start with UID 0 and things should work properly from there.

**Comment by chrisrpatterson** [comment]
> Good to know! If anything, this may be good to have documented somewhere or linked to if this failure shows up again for someone.

I thought it was documented but I just realized it is not. I am putting a PR in for the docs now.
