### ISSUE TITLE
Clang does not appear to work

### ISSUE THREAD

**Issue by misnor** [Microsoft/vsts-agent-docker#149]
I started the agent, connected it to VSTS/Azure Pipelines and triggered a build. When CMake runs it is complaining about Clang not being in the PATH. I can see in the [Dockerfile](https://github.com/microsoft/vsts-agent-docker/blob/f1a2b55a7aeac237ee5ce3fb29b4ed37053462dd/ubuntu/16.04/standard/Dockerfile#L58) that it installs clang, but the comment:

> Install Clang (only appears to work on xenial)

seems to indicate some sort of issue. Does my host OS need to be Xenial (16.04) for this to work? I am on 18.04 right now and I was using the `microsoft/vsts-agent:ubuntu-16.04-standard` image + tag.

See attached output for the error produced during the build through VSTS/Azure Pipelines.

[output.txt](https://github.com/Microsoft/vsts-agent-docker/files/2454065/output.txt)

**Comment by dakale** [comment]
Hi @misnor . Clang is actually installed as `clang-6.0` which should be in the PATH. If you have a lot of calls to `clang` in some scripts that either you cant or dont want to change, you can run something like:

```bash
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-6.0 100
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 100
```

in a script as a first step in your build to map `clang-6.0 -> clang`

To answer your question, the host os doesnt matter. I think "only" works on xenial on meant that it at least _doesnt_ work on trusty (14) which is the other version of images we build

Let me know if that doesnt solve your issue and ill reopen if needed

**Comment by misnor** [comment]
Thank you for the quick response, David - this worked perfectly.
