### ISSUE TITLE
Git LFS support

### ISSUE THREAD

**Issue by anznpatel** [Microsoft/vsts-agent-docker#15]
enabling "checkout files from LFS" via VSTS build definition settings causes a failure in the build
`Git-lfs installation failed with exit code: 1`

tried to install git-lfs by manually ssh-ing into the node where the vsts agent is hosted, via the following commands 
`curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
`apt install git-lfs`

this installed git-lfs successfully but the build still fails as the build agents run in a different environment

**Comment by stepro** [comment]
All the images now support git lfs.
