### ISSUE TITLE
vsts-agent in OpenShift

### ISSUE THREAD

**Issue by fabiostawinski** [Microsoft/vsts-agent-docker#151]
Hello, I run the agent in my machine and it works just perfect. Then I pushed my image to openshift, then I got some permission denied issue:
`./start.sh:` line 19: /vsts/.token: Permission denied

I tried to find how to give these permissions within OpenShift, but I was not able to find yet, someone has any idea?

**Comment by dakale** [comment]
Great. Closing for now, let me know if you run into any more issues
