### ISSUE TITLE
Please support windows server 2019

### ISSUE THREAD

**Issue by AceHack** [microsoft/vsts-agent-docker#157]
This includes for host and containers.

Thanks.

**Comment by AceHack** [comment]
Any update on 1809?

**Comment by olljanat** [comment]
@AceHack as there is no Docker images available for any Windows versions yet it is better to follow general issue about it. Anyway I plan to create template for this if I get confirmation that it will be released to Docker HUB. Look https://github.com/Microsoft/vsts-agent-docker/issues/1#issuecomment-456699288

**Comment by AceHack** [comment]
I’m looking for the same as “Hosted Windows Container” but for 1809 I.e. Windows Server 2019.

**Comment by olljanat** [comment]
Ok. I think that those are created from https://github.com/Microsoft/azure-pipelines-image-generation/ so maybe better to create issue to there.

This repository provides Docker images to https://hub.docker.com/r/microsoft/vsts-agent
