### ISSUE TITLE
Intermittent connectivity from vsts-agent to docker daemon on AKS

### ISSUE THREAD

**Issue by jeffmartinxyz** [microsoft/vsts-agent-docker#159]
I'm working with @SurushS to resolve intermittent vsts-agent / docker daemon connectivity on AKS. He posted the below comment on [54](https://github.com/Microsoft/vsts-agent-docker/issues/54#issuecomment-433353440), but I don't think it has been seen since the issue was closed. 

> I've recently had the same issue. We've been running our vsts agents (microsoft docker hub images with ubuntu) for almost a year now on our AKS cluster (first preview, then GA, now GA with RBAC enabled). We've never changed the deployment yaml (which pretty much looks identical to the one mentioned in the thread). However since moving to the RBAC enabled cluster, it seems that every three days or so the agents lose connection with the docker daemon on the nodes with the same error "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" . This is the case with build steps, but also when i use kubectl exec to log into the containers. The only way i can resolve it is to use the kubectl scale command, scale down to 0, wait for all of them to be terminated and scale back up to the amount i had. Then the docker commands work again. killing and respawning without scaling to 0 does not work. I don't know if it has something to do with the fact that we moved to an RBAC enabled cluster and i need to specify additional permissions in the deployment yaml.

**Comment by azooinmyluggage** [comment]
Hi @jeffmartinxyz,
Can we have a call to troubleshoot this? 

Atul

**Comment by azooinmyluggage** [comment]
Closing this. Please let me know if you are still facing this issue.
