### ISSUE TITLE
MS Build Version changed from 15.6.0.0 to 15.1.8.0

### ISSUE THREAD

**Issue by anand5555** [Microsoft/vsts-agent-docker#162]
I am using hosted agent image for our builds and recently  as we have increased number of build requests, and i have setup a new server and pulled the hosted image and started more agents to support our builds. But nuget restore was failing  with below error. /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.props(27,3): error : Version 2.1.302 of the .NET Core SDK requires at least version 15.3.0 of MSBuild. The current available version of MSBuild is 15.1.8.0. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

I have logged in to the container on newly setup agent and saw ms build version is 15.1.8.0 
![image](https://user-images.githubusercontent.com/31290069/48668105-3a1fac80-eab3-11e8-8a82-2c6a82f1bcf0.png)

Where as our old agent has  15.6.0.0
![image](https://user-images.githubusercontent.com/31290069/48668109-51f73080-eab3-11e8-9d7b-e24cba69f9ad.png)

Note: Nuget restore works perfectly as the msbuild version is 15.6.0.0

Is the version changed in the latest agent image build ? can some one help me ?

**Comment by dakale** [comment]
It looks like maybe mono mistakenly included msbuild 15.1.8 instead of 15.8. Regardless, I updated the ubuntu-16-based images (including latest), they should now be have msbuild 15.8. You should be able to pull updated images 

Let me know if you have an issues
