### ISSUE TITLE
Missing dotnet sdk-2.2

### ISSUE THREAD

**Issue by inputfalken** [Microsoft/vsts-agent-docker#167]
We are currently using this [DockerFile](https://github.com/microsoft/vsts-agent-docker/blob/d9c72fb5d961e37843d8dd0274fb5346022d6852/ubuntu/16.04/docker/18.06.1-ce/standard/Dockerfile) and cannot upgrade to dotnet sdk-2.2.

Would be nice if dotnet sdk-2.2 would be available for Azure DevOps.

**Comment by renardguill** [comment]
Please Microsoft, fix this issues.

**Comment by nodsod** [comment]
Yes please! Very frustrating then trying to build a release to Azure

**Comment by ljani** [comment]
This is fixed by https://github.com/Microsoft/vsts-agent-docker/pull/169 when it gets merged.

@stepro ping.

It's starting to feel like `vsts-agent-docker` is a second class citizen and we should start building the images ourselves. This image seems to updated with a huge delay when for example a new `dotnet` version or TFS version is released.

**Comment by dakale** [comment]
Latest images on dockerhub will now have 2.2

If you need the latest versions of software as soon as they are released, I recommend building your own images based off either vsts-agent:ubuntu-14.04 or 16.04 and installing what you need on there. Keeping all the images up to date with the latest of everything, while not moving too fast and breaking people has been a challenge. Additionally, even something small like bumping the dotnet version will have people downstream pulling multiple gigabytes of image layers, depending on how things are ordered (the full standard image is now ~10gb, which is not suitable for people using eg Kubernetes, where containerized agent makes sense). 

Overall, Im not inclined to rebuild and push new images for every update of every software that is currently on the image. If there is large need (for example, this issue and community need for dotnet 2.2), I can update that particular software. 

It could be set up to automatically build and push on a daily or weekly schedule, which would just pick up changes to the Dockerfiles contributed through PRs, etc, it just puts higher risk on people pulling by tag and not sha, and things unexpected sliding forward. 

Ill continue to think about it, but this project has definitely become lower priority as we moved to building vm-based environments (https://github.com/Microsoft/azure-pipelines-image-generation) which have grown far too bulky to be useful in a container scenario (the full set of software installed would bloat these images by several 10s of more GBs)
