### ISSUE TITLE
SSL certificate subject name error with Azure Devops

### ISSUE THREAD

**Issue by jdamore** [Microsoft/vsts-agent-docker#168]
Hi,

I am trying to launch a microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard VSTS agent in our Azure Kubernetes cluster, to be used with our instance of Azure Devops https://deloittedigitalat.visualstudio.com.

I am currently passing the following values in the kube template: VSTS_ACCOUNT, VSTS_TOKEN, and VSTS_POOL.

When the agent starts, I get the following error:

```
Determining matching VSTS agent...
curl: (51) SSL: certificate subject name (visualstudio.com) does not match target host name 'deloitte.at.visualstudio.com'
```
I looked at the SSL certifciate and I can see that the list of Subject Alternative Name has visualstudio.com but not *.visualstudio.com. Of course I do not control this cert.

I also tried passing in the options CURLOPT_SSL_VERIFYHOST=false or VSTS_SSLSKIPCERTVALIDATION=false but they have no effect (I saw the last one on this issue https://github.com/Microsoft/vsts-agent-docker/issues/124 but could not see how that could work).

Would it be possible to add a flag to bypass SSL validation and run curl -k in the start.sh script?

**Comment by jdamore** [comment]
I appeared that I had the wrong VSTS_ACCOUNT. Now that I have set the VSTS_ACCOUNT to deloittedigitalat, the curl command succeeds.

**Comment by gabrielfsousa** [comment]
i have the same problem, how i know to put on VSTS_ACCOUNT ?

**Comment by ronnytag233** [comment]
@gabrielfsousa  i have same problem, how did you figure out this?

**Comment by arvalaan** [comment]
You have to use {{your_organization}} variable.

**Comment by cinmay** [comment]
@jdamore @gabrielfsousa @ronnytag233 After much searching i figured it out. The VSTS_ACCOUNT is the devops account name. You can get it from your devops urlhttps://dev.azure.com/"This is where you find the account name" or in the DevOps portal -> Organization Settings -> Overview- > Name
