### ISSUE TITLE
Is there/can there be a healthcheck service?

### ISSUE THREAD

**Issue by junkiebev** [microsoft/vsts-agent-docker#175]
Looking inside the container, I see that `port 80` is open for connections and if i hit it with
`$ curl -Lvvv http://localhost`
it spits out a redirect to our visualstudio.com instance

Would it be possible to (perhaps conditionally) add a location like `/healthz` which would just return a `200` response and blank response for getting container health and making scheduling decisions with health checks and such?

**Comment by daveneeley** [comment]
[undocumented](https://github.com/MicrosoftDocs/vsts-docs/issues/285) workaround asking VSTS for the status of the agent:

Get the pool id for the agent 
`https://<name>.visualstudio.com/_apis/distributedtask/pools?api-version=5.0-preview.1`

Get the list of agents `https://<name>.visualstudio.com/_apis/distributedtask/pools/<id>/agents?includeCapabilities=false&includeAssignedRequest=true` 

Find the object with the name matching your agent name and check its status value. Or just get the id from the above and call `https://<name>.visualstudio.com/_apis/distributedtask/pools/<id>/agents/<agent id>`. It seems that the same data is returned.
```
{
_links: {
self: {
href: "https://msi-cie.visualstudio.com/_apis/distributedtask/pools/<pool id>/agents/<agent id>"
},
web: {
href: "https://msi-cie.visualstudio.com/_admin/_AgentPool#_a=agents&poolId=<pool id>&agentId=<agent id>"
}
},
maxParallelism: 1,
createdOn: "2019-03-27T18:57:22.513Z",
id: <agent id>,
name: "<agent name>",
version: "2.149.1",
osDescription: "<agent os>",
enabled: true,
status: "online",
provisioningState: "Provisioned",
accessPoint: "VstsAccessMapping"
}
```

Consolidating this down to a docker-compose healthcheck
```
---
version: '3'
services:
  vsts-agent:
    container_name: 'vsts-agent'
    image: 'mcr.microsoft.com/azure-pipelines/vsts-agent:latest'
    network_mode: 'bridge'
    restart: on-failure
    healthcheck:
      test:
          - "CMD-SHELL"
          - >
              poolid=`curl -fsS "https://<account name>.visualstudio.com/_apis/distributedtask/pools?api-version=5.0-preview.1"
              -u "<agent name>:<agent token>" | jq --arg poolname "<pool name>" '.value[] | select(.name == $$poolname) | .id'`;
              curl -fsS "https://<agent name>.visualstudio.com/_apis/distributedtask/pools/$$poolid/agents"
              -u "<agent name>:<agent token>" | jq --arg agentname "<agent name>" '.value[] | select(.name == $$agentname) | .status' | grep online

```
