### ISSUE TITLE
Edit Docker Hub description: add Deprecated note

### ISSUE THREAD

**Issue by froblesmartin** [microsoft/vsts-agent-docker#185]
Hi!

Here in your repo you show that this is deprecated, but people reaching first to the Docker Hub repository, doesn't know about this.

You should upload this page to announce it: https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent?tab=description

Cheers!
Francisco Robles Martín

**Comment by PirateBread** [comment]
Frustrating that MS don't also provide the docker images as they previously did.
Now I have to run a packer build to generate my _own_ image and create my own docker containers. I'm sure there's a good reason, it just feels like a backwards step when previously it would take a few minutes to deploy a VSTS agent from a docker image.

**Comment by faur8** [comment]
Hey @PirateBread what are you using currently instead of this image?

Thanks!

**Comment by kwaazaar** [comment]
This repo seems abandoned as well. First link in the readme is already broken.

**Comment by kirkone** [comment]
Hi @PirateBread and @faur8 you can have a look here:
https://github.com/codez-one/docker-azure-pipelines-agent
I started creating my own images. Please have a look and give some feedback.

Images can be found here:
https://hub.docker.com/r/czon/azdo-agent
