### ISSUE TITLE
Invalid configuration provided for username. Terminating unattended configuration.

### ISSUE THREAD

**Issue by seven1986** [Microsoft/vsts-agent-docker#19]
```
?1h=
>> End User License Agreements:
Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.
A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html
>> Connect:
Invalid configuration provided for username. Terminating unattended configuration.
```

**Comment by stepro** [comment]
Which image tag are you using?

**Comment by seven1986** [comment]
Hi, @stepro, here is my command line
```
docker run
-e VSTS_ACCOUNT=wangzhen 
-e VSTS_TOKEN=gjnj6ufstxpkzfheua2cuisqz*****************q 
-e TFS_HOST=https://tfs.agmostudio.com/tfs 
-it microsoft/vsts-agent:ubuntu-16.04-tfs-2017-docker-17.03.0-ce-standard
```

![image](https://cloud.githubusercontent.com/assets/20808494/24824974/3533a0ea-1c48-11e7-95fa-43c7d80103fa.png)

**Comment by stepro** [comment]
It looks like you are using TFS_HOST but providing a full URL to your server. Try setting the TFS_URL environment variable instead.

**Comment by seven1986** [comment]
It still tell me the same error
```
Invalid configuration provided for username. Terminating unattended configuration.
```

**Comment by seven1986** [comment]
![image](https://cloud.githubusercontent.com/assets/20808494/24835795/071ba0ee-1d3e-11e7-853a-57e998f58f75.png)

my account：wangzhen
              or ：AGMOSTUDIO\wangzhen

here is token：
7v4m2gzmwwpw4wbb76x3tvzdjic6hvsuz2iw5fcorvhqv6ntk5xq

server：https://tfs.agmostudio.com/tfs

I try  many times， always can not work....

please have a try，thanks a lot!

**Comment by stepro** [comment]
Ok, the token is not being passed in the command line. See #10, and #20.
