### ISSUE TITLE
Not found docker: null

### ISSUE THREAD

**Issue by coreyperkins** [Microsoft/vsts-agent-docker#2]
Anybody seen this one, with the latest ubuntu-16.04 image?

sudo docker run -e VSTS_ACCOUNT="myaccount" -e VSTS_TOKEN="mytoken" -e VSTS_AGENT="docker" -v /var/run/docker.sock:/var/run/docker.sock -it microsoft/vsts-agent:ubuntu-16.04

The agent gets connected to our vsts but when a build is triggered we get that message (Not found docker: null).

Thanks for any and all help.

Corey

**Comment by stepro** [comment]
The problem is likely because your image doesn't include the docker CLI. Try using "microsoft/vsts-agent:ubuntu-16.04-docker-<ver>" where <ver> is 1.11.2 or 1.12.1 depending on your host daemon version.

**Comment by coreyperkins** [comment]
Thanks Stephen! I'm new to vsts and this was a big help!
