### ISSUE TITLE
Is it possible to run the agent as a docker service?

### ISSUE THREAD

**Issue by jorisdebock** [Microsoft/vsts-agent-docker#21]
Is is possible to run the agent as a docker service?

I tried to following without success.
```
docker service create \
  --name=vsts-agent \
  --constraint=node.role==manager \
  --env VSTS_ACCOUNT=<account> \
  --env VSTS_AGENT=<agent> \
  --env VSTS_POOL=<pool> \
  --env VSTS_TOKEN=<token> \
  --env VSTS_WORK='/var/vsts/$VSTS_AGENT' \
  --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
  --mount=type=bind,src=/var/vsts,dst=/var/vsts \
  --tty microsoft/vsts-agent:latest
```

**Comment by stepro** [comment]
I would *think* that this should work. What's the error you are seeing?

**Comment by jorisdebock** [comment]
I am not seeing any error, that is kind of the problem. 

The "docker service create" command just schedules the task so I am not able to see direct output messages. If I try to read the logs with "docker service logs" it will return that this is not possible with the "--tty" parameter. If I leave out the "--tty" parameter the logs command returns empty.

**Comment by jorisdebock** [comment]
Ok I just tried again with the above command and suddenly it is working as expected. No idea why the first 15 times it didn't work and now it does all the time... The only thing that has changed is that I also created a docker service with portainer, but that shouldn't make a difference.

**Comment by stepro** [comment]
Ok, let me know if you run into the problem again. Closing the issue for now.
