### ISSUE TITLE
Using Docker Containers to build source inside VSTS Docker Agent

### ISSUE THREAD

**Issue by jsturtevant** [Microsoft/vsts-agent-docker#22]
When using the ```docker``` image ```microsoft/vsts-agent:ubuntu-16.04-docker-17.03.0-ce-standard```
 as VSTS build agent on a linux machine, after my step to build the code files are not being outputted.  I am using a docker container to do the build and have the output mapped to a volume on the container that is being used for the build.  

I believe this is because the docker commands are be passed to the host through the volume map ```-v /var/run/docker.sock:/var/run/docker.sock``` ([as per the documentation](https://hub.docker.com/r/microsoft/vsts-agent/)). It seems the context in which the docker command runs, docker volume mounts are not mapping to the agent container.
		
I end up with errors like: 
		
```
[command]/usr/local/bin/docker-compose -f /vsts/agent/_work/1/s/docker-compose.build.yml -p web-front up unit-tests
2017-04-14T01:37:56.4851300Z Starting webfront_unit-tests_1
2017-04-14T01:38:00.2561860Z Attaching to webfront_unit-tests_1
2017-04-14T01:38:00.2586250Z [36munit-tests_1     |[0m MSBUILD : error MSB1009: Project file does not exist.
2017-04-14T01:38:00.2618300Z [36munit-tests_1     |[0m Switch: ./WebFront.Tests/WebFront.Tests.csproj
2017-04-14T01:38:01.4295840Z [36mwebfront_unit-tests_1 exited with code 1
2017-04-14T01:38:01.5604130Z ##[section]Finishing: build-test
2017-04-14T01:38:01.6217030Z ##[section]Starting: build image
```
	
and 

```
Step 4/5 : ENTRYPOINT dotnet WebFront.dll
2017-04-14T01:38:03.0085400Z  ---> Using cache
2017-04-14T01:38:03.0100830Z  ---> 9fce6802ad0c
2017-04-14T01:38:03.0114590Z Step 5/5 : COPY ./obj/Docker/publish/ .
2017-04-14T01:38:03.0135350Z Service 'build-image' failed to build: lstat obj/Docker/publish/: no such file or directory
```

This seems similar to #13.  

## Possible Solution
I was able to make it work by mapping the agent working folder ```/vsts/code/_work``` when booting the agent:

```
docker run \
  -e VSTS_ACCOUNT=<account> \
  -e VSTS_TOKEN=<token>  \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/vsts:/var/vsts \
  -v /vsts/agent/_work:/vsts/agent/_work
  -d microsoft/vsts-agent:ubuntu-16.04-docker-17.03.0-ce-standard
```

I am not sure if this is the best way to make it work but the build did complete.  If this is the best way, this doesn't work out of the box as the ```start.sh``` script doesn't support mounting the ```/vsts/agent/_work``` folder.  When the [start.sh](https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/start.sh) script starts it check and removes the ```/vsts/agent/folder``` and everything under it:

```
#snippet of start.sh
if [ -e /vsts/agent -a ! -e /vsts/agent/.agent ]; then
  rm -rf /vsts/agent
fi
```

which causes the following error when the docker container starts:

```
rm: cannot remove '/vsts/agent/_work': Device or resource busy
```

I was able to get it to work by modify the ```start.sh``` script. A working example is: https://github.com/jsturtevant/vsts-agent-docker-temp-fix.  I will submit a PR for the change though again not sure if this is the best way to solve the issue.

**Comment by stepro** [comment]
The right way to do this is to set the VSTS_WORK environment variable to a location other than under /vsts/agent, say under /var/vsts, and then volume map the /var/vsts folder.

**Comment by stepro** [comment]
Closing this issue; let me know if the solution I suggested isn't working for you.

**Comment by jsturtevant** [comment]
Thanks, adding the environment variable and volume mapping the location worked!  Much simpler.

**Comment by leontyr** [comment]
Is it possible to use "Hosted Linux Preview" agent to build docker project? If yes, where can I add VSTS_WORK?

**Comment by stepro** [comment]
You should be able to use the hosted Linux preview agent, at which point you don't need to specify VSTS_WORK - that is already configured by the hosted agent. Is there a specific issue you are having with the sample code you attached where it is not working?

**Comment by leontyr** [comment]
It's in the build on VSTS. Here is the error:

```
2017-08-03T13:49:29.7870050Z Step 5 : COPY ${source:-obj/Docker/publish} .
2017-08-03T13:49:29.7887410Z lstat obj/Docker/publish: no such file or directory
2017-08-03T13:49:29.8020070Z ##[error]lstat obj/Docker/publish: no such file or directory
2017-08-03T13:49:29.8091540Z [command]/usr/bin/docker logout london.azurecr.io
2017-08-03T13:49:29.8107480Z Remove login credentials for london.azurecr.io
2017-08-03T13:49:29.8156690Z ##[error]/usr/bin/docker failed with return code: 1
```

**Comment by stepro** [comment]
@thechrisjohnson, how do you configure the VSTS agent work folder in the hosted Linux build agent? The host directory and the directory in the container must be the same for this scenario to work.

**Comment by thechrisjohnson** [comment]
For the Hosted Linux Preview pool, the agent is actually running in a container with the docker.socket file mapped in from the host. The work folder for the agent is directly mapped from the Host too (/opt/vsts/work of the host to /opt/vsts/work in the container). You should be able to figure out the full path of the file you want to copy into the container and the same file will exist on the Host.

**Comment by stepro** [comment]
Ok, based on this setup, the scenario should work. @leontyr, can you describe what you are doing in your build definition? I am assuming you run a docker-compose task that consumes docker-compose.ci.build.yml which when run, should output the obj/Docker/publish directory. Then in the subsequent Docker build task, it's failing to locate the files that were just built. Is that correct?

**Comment by leontyr** [comment]
My build was created by Continuous Delivery Tools for Visual Studio. Looking at the definition, it contains 'Get sources', 'Build an image preview docker' and 'Push an image preview docker'. 'Docker Compose' is not there.

**Comment by stepro** [comment]
Ok, there is likely a tools mismatch problem here. You managed to get a docker-compose.ci.build.yml file into your project, but the CD tools for VS don't know how to take advantage of that file. You'll need to add a task that actually invokes your docker-compose.ci.build.yml file so that the compilation steps occur before trying to build your Docker image. Take a look at the "Docker Compose" task and look for the action that allows you to run a specific service. You'll want to choose your docker-compose.ci.build.yml file and pick the "ci-build" service as the one to run.

**Comment by jsturtevant** [comment]
Sounds like it might be something else but I was able to get this working with the following.  (should have posted it back when i got it working):

```
docker run -e VSTS_ACCOUNT=<youraccountname>  \
  -e VSTS_TOKEN=<your-account-Private-access-token> \
  -e VSTS_WORK=/var/vsts -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/vsts:/var/vsts -d \ microsoft/vsts-agent:ubuntu-16.04-docker-17.03.0-ce-standard
```

I did a [blog post](http://www.jamessturtevant.com/posts/Using-the-VSTS-Docker-Agent/) on it a while back  if you want more details about all the different settings.

**Comment by leontyr** [comment]
Ok, let me give it a go. Thank you, guys!

**Comment by uhaciogullari** [comment]
I don't understand how the suggested solution fixes the problem. I am not a Docker expert but it seems like running this command starts a container locally and it doesn't affect the hosted agents on VSTS. My builds are still failing with the same error.

> Service 'myservice' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder762830029/obj/Docker/publish: no such file or directory

**Comment by uhaciogullari** [comment]
Just to help the poor souls who are struggling with the same issue: I was able to fix the problem by modifying the docker-compose.yml.

This will get the error above:
```
version: '3.4'

services:
  myproject:
    image: myproject
    build:
      context: ./MyProject
      dockerfile: Dockerfile
    links:
      - myotherproject

```


This works
```
version: '3.4'

services:
  myproject:
    image: myproject
    build:
      args:
        source: .
      context: ./MyProject
      dockerfile: Dockerfile
    links:
      - myotherproject

```

**Comment by biswajeetbehera** [comment]
#I am getting below error while trying to build an image
#E: Unable to locate package oracle-java8-installer‌



Get:2 http://ppa.launchpad.net trusty/main Sources [20 B]
Get:3 http://ppa.launchpad.net trusty/main amd64 Packages [20 B]
Fetched 15.5 kB in 5s (2737 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package oracle-java8-installer‌
E: Unable to locate package oracle-java8-set-default
The command &#x27;&#x2F;bin&#x2F;sh -c echo &#x27;deb http:&#x2F;&#x2F;ppa.launchpad.net&#x2F;webupd8team&#x2F;java&#x2F;ubuntu trusty main&#x27; &gt;&gt; &#x2F;etc&#x2F;apt&#x2F;sources.list &amp;&amp;     echo &#x27;deb-src http:&#x2F;&#x2F;ppa.launchpad.net&#x2F;webupd8team&#x2F;java&#x2F;ubuntu trusty main&#x27; &gt;&gt; &#x2F;etc&#x2F;apt&#x2F;sources.list &amp;&amp;     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886 &amp;&amp;     apt-get update &amp;&amp;     echo oracle-java${JAVA_VER}-installer shared&#x2F;accepted-oracle-license-v1-1 select true | sudo &#x2F;usr&#x2F;bin&#x2F;debconf-set-selections &amp;&amp;     apt-get install -y --force-yes --no-install-recommends oracle-java${JAVA_VER}-installer oracle-java${JAVA_VER}-set-default &amp;&amp;     apt-get clean &amp;&amp;     rm -rf &#x2F;var&#x2F;cache&#x2F;oracle-jdk${JAVA_VER}-installer&#x27; returned a non-zero code: 100‌
##[error]The command '/bin/sh -c echo 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' >> /etc/apt/sources.list &&     echo 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' >> /etc/apt/sources.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886 &&     apt-get update &&     echo oracle-java${JAVA_VER}-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections &&     apt-get install -y --force-yes --no-install-recommends oracle-java${JAVA_VER}-installer oracle-java${JAVA_VER}-set-default &&     apt-get clean &&     rm -rf /var/cache/oracle-jdk${JAVA_VER}-installer' returned a non-zero code: 100
##[error]/usr/bin/docker failed with return code: 100
##[section]Finishing: Build an image
