### ISSUE TITLE
Using TFS_HOST environment variable not working for TFS server

### ISSUE THREAD

**Issue by getrostt** [Microsoft/vsts-agent-docker#25]
When using the `vsts-agent-docker` in combination with an on premise TFS 2017 server using the `TFS_HOST` environment variable produces a http url. As mentioned in [vsts-agent Issue 695](https://github.com/Microsoft/vsts-agent/issues/695) the authentication with a PAT token requires a https connection.

I am aware that I can set the url using the `TFS_URL` environment variable to configure the correct https url. 

Anyway it would make sense to change the url build from the `TFS_HOST` environment variable a https url as it required anyway.

**Comment by stepro** [comment]
I think this makes sense. Is the default port of 8080 still the right port to use for https, or should it be changed to 443?

**Comment by getrostt** [comment]
Sorry, for the late response. Port 8080 makes indeed not much sense when using HTTPS. Port 443 as default sounds reasonable to me.

**Comment by stepro** [comment]
The images have been updated to use https://$TFS_HOST/tfs as the default TFS_URL.
