### ISSUE TITLE
issue with connecting to vsts

### ISSUE THREAD

**Issue by Hirayuki** [Microsoft/vsts-agent-docker#26]
i have already opened an issue:

https://github.com/Microsoft/vsts-agent/issues/943

should I copy here ?

*************
I have a docker cluster behind a VPN. And also I have a TFS on visualstudio.com, I have downloaded TFS agent container, and want to connect to our TFS but it cannot connect with an alarm of:

```
Determining matching VSTS agent...
Downloading and installing VSTS agent...
curl: (35) gnutls_handshake() failed: Error in the pull function.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
It can ping google.But cannot ping public TFS. I would consider this as a network issue but nginx container was pulled and started with success.
```
  docker run \
  -e VSTS_ACCOUNT= xxx \
  -e TFS_HOST= yyy \
  -e VSTS_TOKEN= zzz \
  -it microsoft/vsts-agent
```
also tried this:

```
docker run \
  -e VSTS_ACCOUNT= xxx \
  -e VSTS_AGENT='$(hostname)-agent'\
  -e VSTS_TOKEN= yyy \
  -e TFS_URL= zzz \
  -e VSTS_POOL= eee \
  -e VSTS_WORK='/var/vsts/$VSTS_AGENT' \
  -v /var/vsts:/var/vsts \
  -it microsoft/vsts-agent:ubuntu-14.04
```
Although it is behind VPN, I can access the repo from browser btw.

**Comment by stepro** [comment]
If you run an arbitrary image (e.g. ubuntu:16.04) and try to curl/ping something.visualstudio.com, does it work?

**Comment by Hirayuki** [comment]
ping is not working. tried arbitrary image

**Comment by stepro** [comment]
It looks like ping doesn't work against *.visualstudio.com addresses (even without VPN, it isn't working). Can you try curl instead (and if it doesn't work, include -v for verbose output)?

**Comment by Hirayuki** [comment]
curl did not find any problems, it shows it is redirected to another link. which certificate is use while connecting to VSTS server and in which port by default?

**Comment by stepro** [comment]
Ok, getting further. It seems to be a problem specific to the download URL for the correct version of the VSTS agent. I believe that is actually a reference to GitHub. Do you have any VPN restrictions around access to github.com?

**Comment by Hirayuki** [comment]
Thanks @stepro . Found the issue. I have added IP to white list, and everything worked. It seems IP was blocked and it was shown as SSL issue, wget also was not working.
