### ISSUE TITLE
Container can't restart after stop

### ISSUE THREAD

**Issue by stffabi** [Microsoft/vsts-agent-docker#29]
We are using the TFS on prem container images and currently have the problem that sometimes when the container gets stopped, the agent registration is not removed. Therefore after a restart of the container, the container exits with the information 

```
agent_1  | Cannot configure the agent because it is already configured. To reconfigure the agent, run 'config.cmd remove' or './config.sh remove' first.
```

The only possibility to bring it up again, is to completely remove the container and create a new one.

**Comment by stepro** [comment]
I don't think this is the right way to solve this problem. There was some previous changes to the unversioned script (ubuntu/start.sh) that addressed this issue in a manner that better reflects how it would work in an uncontainerized environment. Basically, on startup, the container determines if it was previously running and if so, it executes a fast path to restarting the agent process with the existing configuration. Dropping the configuration and recreating it seems unnecessary. I'm not sure why I didn't make the equivalent changes to the TFS versioned images. I'll play with it now and see if I can ensure a consistent behavior across all the images that solves this problem.

**Comment by stepro** [comment]
Looking back at things, this change makes sense. The unversioned and versioned scenarios are different and I think the behavior here is the most appropriate thing. I'm making a few fixes around restart in the unversioned case and will push these changes (along with some others) today, and rebuild and push the images.
