### ISSUE TITLE
TFS versioned images shuold take a full TFS Url instead of VSTS account.

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/vsts-agent-docker#3]
The TFS images are targeted on TFS users not VSTS users and the expectation to configure the agent will be the URL of your TFS server instead of your VSTS account.

**Comment by ups216** [comment]
Is this working with TFS 2017 at all? I was excited about the tag "ubuntu-16.04-tfs-2017" but found no document on how I can run it and connect to TFS 2017.

**Comment by stepro** [comment]
We should have this working and fully documented in about two weeks.

**Comment by ups216** [comment]
thanks @stepro
It will be great if we can do agentless configuration. Trigger build will docker run an agent then do the work inside the container and then clean up the agent totally.

**Comment by stepro** [comment]
@ups216 I think that's a desired scenario eventually. @chrisrpatterson can comment more on the work they are doing around Dockerizing of agents in general.

**Comment by stepro** [comment]
I just pushed updates to the README.md that describe how the TFS images can be used. Please take a look and see if it works for you. It remains unclear to me how authentication works for the on-prem TFS scenario.

**Comment by magol** [comment]
How do I do if my TFS 2017 server use a self signed https?
I only get errors if I try to use it, so I guess it must have the certificate to access the server.

**Comment by stepro** [comment]
For that to work, I believe you'll need to derive a new image from the existing image and register your specific SSL certificate as trusted. Depending on how you are running the image, you might also be able to volume map the certificate file(s) into the container when you run it.
