### ISSUE TITLE
Docker version support

### ISSUE THREAD

**Issue by newtack** [Microsoft/vsts-agent-docker#32]
Per https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/docker/1.12.1/standard/Dockerfile it looks like you only support docker version 12. 
When is support for 17 planned for, especially looking for multistage build support

**Comment by stepro** [comment]
The [README](https://github.com/Microsoft/vsts-agent-docker/blob/master/README.md) describes images for docker 1.11.2, 1.12.1 and 17.03.0-ce. Multi-stage build support is available in 17.05.0-ce, but this is not a stable channel release. We'll publish an official image with the next stable release, which I believe will be 17.06.0-ce. If you want to try multi-stage build before then, you can take the ubuntu-16.04-standard image and apply your own version of docker on top of it as a derived image similar to [this](https://github.com/microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/docker/17.03.0-ce/standard/Dockerfile). Just replace the DOCKER_VERSION, DOCKER_SHA256 and DOCKER_COMPOSE_VERSION environment variables with the version you want.

**Comment by newtack** [comment]
Thanks for your helpful answer.
