### ISSUE TITLE
Windows Container Host/Image repo

### ISSUE THREAD

**Issue by jabbera** [microsoft/vsts-agent-docker#33]
It would be great if I could point TFS or VSTS at an image repo and a container host (Server 2016) and it could manage the lifetime for me. There isn't really a need to keep the image up and running all the time. When a build request hits the pool can start a docker image, do the build, save the artifacts, then rmi the image. People can mutate the build environment as they need as part of the build and the changes just get swept away at the end.

**Comment by stepro** [comment]
@chrisrpatterson, this is an interesting suggestion for how someone could enable their own on-demand agent pool without changing the design of the VSTS agent. Perhaps there could be a special type of pool that is configured with a container host and image and it would be able to easily start up an agent as needed and throw it away at the end. Thoughts?

**Comment by jabbera** [comment]
I glossed over it but it would also significantly reduce the number of build environments (images) we need to maintain. As part of the build users can install any 3rd party applications they need to build since we can let them run as admin in the docker container. The environment is epeheremal so they can install whatever they want (ala appveyor).

**Comment by jabbera** [comment]
Hi. Just curious if there has been any internal discussion about this possibility. I'm so tired of managing everyones build machines:-)

**Comment by gravufo** [comment]
I'll add my voice to this. It would be very helpful to any build master!

**Comment by Rabadash8820** [comment]
> There isn't really a need to keep the image up and running all the time.

> this is an interesting suggestion for how someone could enable their own on-demand agent pool without changing the design of the VSTS agent.

@jabbera These two quotes sum it all up in my mind.  Seems like this could be implemented with modest effort, and it would give VSTS a much more robust way to handle CI/CD.  +1 for sure!

**Comment by dakale** [comment]
This is an area that is currently receiving some effort. I will make sure to update here as solutions become available in the next few weeks/couple months

**Comment by gregpakes** [comment]
This is exactly what I'm looking for.  I am looking at running Azure Container Instances in order to leverage the per second billing.  I would love to be able to spin up my own private agent in a container, run the build and then shut it down.

I have been looking at manual ways to implement this.  Are you saying this is something that is being looked into?  I want to know whether it's worth my effort to look into a manual solution.

**Comment by dakale** [comment]
Yes, a comparable solution is being developed first party, but I cannot comment on when it will be GA. 

In the meantime, a manual solution is possible if you are willing to get your hands dirty. Check out this recent post by a MSFT engineer: https://www.noelbundick.com/posts/serverless-vsts-build-agents-with-azure-container-instances. Its pretty clever and I think closely matches your needs

**Comment by gregpakes** [comment]
@dakale Yes - I've seen this and was going to base my solution on it.  It lacks some basic things, for instance it assumes only one build will run at a time, so there will need to be changes made there.

I know I'm about to ask the impossible, do you have any indication of whether the first party solution is 1 month or 1 year away?  I'm not looking for a deadline or a promise, just a vague indication.  If it is 1 year away, I will probably make my own system.  If it is 1 month away, I will probably wait.

**Comment by dakale** [comment]
Its hard to say but not impossible. My best estimate would be in the 3-6mo range, but theres a lot of variables contributing to that number that are out of my control. Its not great but I hope that helps. I can say thought that this is something that is frequently asked for, so we are committed to solving this issue one way or another

**Comment by gregpakes** [comment]
@dakale - This is definitely helpful.  Thanks.

**Comment by kbdavis07** [comment]
Is there a way to have a VSTS Task to use Azure Container Instances?

Have it work similar to the Azure Web App and other Tasks run on VSTS?

Ability to link to subscription and etc, and in the actual task just include the Azure Container Instance info that is needed to run the Container?

**Comment by jabbera** [comment]
@dakale might you have something for ignite? :-)
