### ISSUE TITLE
CMake in Linux docker images?

### ISSUE THREAD

**Issue by lisaong** [Microsoft/vsts-agent-docker#34]
My team uses CMake in our builds.  We would love to use Hosted Linux Agent preview for our continuous integration builds in the cloud, but currently the images have CMake on them, so we have to setup a local Linux box in the default queue. 

Is it possible to update the docker images to install CMake (the same version that's support in the hosted Windows machines)?

**Comment by stepro** [comment]
@thechrisjohnson, any concerns with adding cmake to the standard images?

**Comment by thechrisjohnson** [comment]
No, I don't think that would be a problem. And I'm sure other people would benefit from it being added.

**Comment by ppanyukov** [comment]
@lisaong You can always package your version of CMake into a docker image and do `docker run` on the hosted linux agent. That's what we do with all our tools. And if you are too lazy, you can do `sudo apt-get install whatever`. Last time I checked, this worked too (a bit worrying but hey!).

**Comment by lisaong** [comment]
Thanks for all the suggestions, I'll give the custom docker image a try.

________________________________

**Comment by shmatkotija** [comment]
We are also trying to use the Hosted Linux Pipeline and interested in using cmake. Thanks!

**Comment by stepro** [comment]
The official standard Docker images have been updated to include cmake.
