### ISSUE TITLE
How to use the VS2017/Dockerfile?

### ISSUE THREAD

**Issue by julioct** [microsoft/vsts-agent-docker#35]
Found this docker file in this repo:
**windows/servercore/10.0.14393/standard/VS2017/Dockerfile**

Which seems to use this as the base image:
**microsoft/vsts-agent:windows-10.0.14393**

However if I do docker pull microsoft/vsts-agent:windows-10.0.14393 I get this:
**Error response from daemon: manifest for microsoft/vsts-agent:windows-10.0.14393 not found**

How to use that docker file?

**Comment by stepro** [comment]
The Windows container Dockerfiles are a work in progress. I believe there is a blocking issue related to licensing right now. @chrisrpatterson, can you comment?

**Comment by StefanScherer** [comment]
Seems like you have to build the base image first with this: windows/servercore/10.0.14393/Dockerfile

**Comment by jmezach** [comment]
Any updates on this? Is there still a licensing issue? I would love to put our on-premises agents into containers.

**Comment by habeebtc** [comment]
Any update?

I also had the unpleasant experience of trying to make the docker packages out on GitHub work with the new Azure Container Instances, only to find that the image microsoft/vsts-agent:windows-10.0.14393  has been pulled from the public repo.

It looks like the only option is to roll one's own?  Is there a way to make this work via Docker Swarm with Windows nodes?

**Comment by dogtail9** [comment]
I also want an update on this. Trying to create a Docker image with the BuildAgent on Windows. I tried most of the stuff google told me to. Use old version of microsoft/windowsservercore but I get the same error every time. The chocolatey packages for the Visual Studio workloads exits with the error code 1.
