### ISSUE TITLE
Copy files not working on the Windows Image creation

### ISSUE THREAD

**Issue by fabiostawinski** [microsoft/vsts-agent-docker#36]
When I tried to create the image it got this error:

```
Step 5/6 : COPY ./Start.* ./
No source files were specified
```

Seems that the copy is not working to copy my context to the image.

**Comment by aumanjoa** [comment]
Hi 
That is working perfectly for me. 
Have you validated that the Start.cmd and Stars.ps1 is in the same directory as your Dockerfile where you run the docker build command?

**Comment by fabiostawinski** [comment]
Yes, they are
