### ISSUE TITLE
Request: ubuntu-16.04-docker-17.06.0-ce

### ISSUE THREAD

**Issue by djeeg** [Microsoft/vsts-agent-docker#41]
Hi 

Really digging the upgrades to [VSTS+Docker integration] and [Azure+Container Registry] that have happened in the last 6 months. Its so much easier to get going.

Unfortunately I have upgraded all my images to multi-stage build, and I balk at having to re-provision my own agent host.

The new verison of docker has been out for a while, is there an ETA on the new agent container being created?
https://docs.docker.com/release-notes/docker-ce/#17060-ce-2017-06-28
As per the release cycle announcement, this version should be around for 3 months.
https://blog.docker.com/2017/03/docker-enterprise-edition

Also how long till the Linux Hosted Preview agent pool within VSTS is updated with 17.06?

Cheers

**Comment by stepro** [comment]
This image is now available.

**Comment by stepro** [comment]
To be clear, it is NOT yet available in the Linux Hosted Preview agent pool, only the docker hub images have been provided.

**Comment by AdnanCukur** [comment]
I'm getting

# docker images
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Running the standard version of the image on a windows host

**Comment by stepro** [comment]
Did you volume map the docker socket into the container?

**Comment by AdnanCukur** [comment]
Gaah! Thanks 👍

**Comment by AdnanCukur** [comment]
For some reason my vsts-agent can't connect to my docker-registry when i try pushing my image there, 

I'm running these commands
docker build . -t docker-registry:5000/adoit
docker push docker-registry:5000/adoit

The push refers to a repository [docker-registry:5000/adoit]
Get https://docker-registry:5000/v2/: dial tcp: lookup docker-registry on 139.162.139.5:53: no such host
/usr/local/bin/docker failed with return code: 1
/usr/local/bin/docker failed with error: /usr/local/bin/docker failed with return code: 1

heres my compose for the vsts agent and docker registry 

version: '3.1'
services:
  vsts-agent:
    image: 'microsoft/vsts-agent:ubuntu-16.04-docker-17.06.0-ce-standard'
    restart: unless-stopped
    environment:
      - VSTS_ACCOUNT=myaccount
      - VSTS_TOKEN=supersecrettoken
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  docker-registry:
    image: 'registry:2.6.2'
    restart: unless-stopped


Edit: If i add 127.0.0.1 docker-registry to my etc/hosts file on my windows host machine it seems to work

**Comment by stepro** [comment]
The reason this isn't working is because docker is running on the host and you are accessing the daemon via your vsts-agent container. The docker-registry instance you are running is part of your composed set of containers and on a special network that the host can't directly access. This is why DNS resolution of "docker-registry" doesn't work. It doesn't explain why mapping docker-registry to 127.0.0.1 makes it work; I assume you must be publishing the docker-registry port 5000 to the host. If you are doing that, then the way to access your registry would be via "http://localhost:5000" rather than "https://docker-registry:5000".

**Comment by AdnanCukur** [comment]
Yeah i published port 5000 to the host but I really don't want to do that.

How would you suggest I connect the vsts-agent to the docker registry ?

**Comment by stepro** [comment]
I don't know of another way of running a local registry that would work. You could try docker-in-docker, but I wouldn't recommend that. What's behind your concern about running a registry on the same host as the Docker daemon? The port doesn't need to be accessible outside of the local machine.
