### ISSUE TITLE
Dockerfile for windows failing on visualstudio installation

### ISSUE THREAD

**Issue by flatwound** [microsoft/vsts-agent-docker#46]
Hi,

i've used the dockerfiles for windows in the past  with success, but currently when I try to rebuild it, it fails on the step installing visual studio 2017 enterprise (chocolatey fails to install it with error code 255).
I've tried to download the vs_enterprise.exe from aka.ms directly and try to install that, but no matter what, I can't get it installed. Anybody have a suggestion?

**Comment by fgather** [comment]
Hi,

I can reproduce the issue. Same with the professional version. Did you find a solution yet?

**Comment by jmezach** [comment]
I saw the same issue when I used version 10.0.14393.1593 of the microsoft/windowsservercore base image. The reason it fails is because of some WPF dll that is missing, which causes the installer to crash.

Moving down to 10.0.14393.1358 of microsoft/windowsservercore fixed that problem, but now the installer just takes a long time. So far my builds have timed out after two hours.

**Comment by fgather** [comment]
Thanks, falling back to the old windows image solved at least the vs installation issue!

**Comment by jorgearteiro** [comment]
I published mine here: https://hub.docker.com/r/jorgearteiro/vsts-agent-vs2017/ with some comments.
I will create a Pull Request.
Try build with docker build -m 4gb -c 2 -t <your image name> .
Something with docker build on Windows. Should take 2 hours when you do that.
I am using microsoft/windowsservercore:10.0.14393.1480 as base image now, but it's not on Dockerhub yet. I will push soon.

**Comment by heaths** [comment]
We are aware of a change that prevents the bootstrapper from loading WPF as of .1593. As you noted, using an older tag will work around this. If you want to decrease install time and container image size, you can also pass `--nocache` and choose what workloads you want using `--add` as described at https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio.

**Comment by judavi** [comment]
Is not working anymore with FROM microsoft/windowsservercore:10.0.14393.1358. The latest version of VS Installer gives a:
Installing visualstudio2017enterprise...
ERROR: Running ["C:\chococache\visualstudio2017enterprise\15.2.26430.20170605\vs_Enterprise.exe" --includeOptional --pa
ssive --norestart --locale en-US --wait ] was not successful. Exit code was '5003'. See log for possible error message
s.
The install of visualstudio2017enterprise was NOT successful

**Comment by heaths** [comment]
Please note that Visual Studio in containers is not supported. We are working to support Build Tools.

If you are using VS in a licensed manner, I cannot diagnose anything based on the information provided. Please see https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container for how you can collect logs if an install fails.

**Comment by judavi** [comment]
Just for the record, more than an issue with the container the 5003 error is an issue with the proxy. But there's no way to setup the proxy using powershell (and the VS installer)

**Comment by judavi** [comment]
@heaths following your example I found -> [know issues](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container-issues) 
So how you avoid the 20 GB limitation? or how you configure Docker to accept images larger than 20 GB?

**Comment by heaths** [comment]
See https://docs.microsoft.com/visualstudio/install/build-tools-container. Note that "storage-opts" does not appear to be supported in 17.06-ee, but has been working for me for several stable versions of 17.x for Windows 10.

**Comment by jjburr** [comment]
Can someone share with me the what daemon configuration change is required for windows containers to increase the size during build so its > 20 ?

**Comment by heaths** [comment]
It's in the docs already: https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container#step-4-expand-maximum-container-disk-size

Also, anyone wanting to ask a question or file a bug not related to the original issue, please open a new one.

**Comment by danielhalati** [comment]
Does anyone installed VS 2013 Express inside Docker? I cannot use Build Tools 2015. I need 2013 compiler. I am using this image microsoft/windowsservercore:10.0.14393.1358

The command I am running to install is:
RUN "C:\\wdexpress_full.exe \Q"

Nothing happens, it just hangs there for several minutes.
