### ISSUE TITLE
Add image for TFS 2018

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-agent-docker#52]
With TFS 2018 being RTM a agent image for it should be available

**Comment by stepro** [comment]
I can do this. @chrisrpatterson, @thechrisjohnson, what's the agent version I should use for TFS 2018 RTM?

**Comment by hanxinimm** [comment]
@stepro it is vsts-agent-win7-x64-2.122.1.zip

**Comment by stepro** [comment]
@hanxinimm, there isn't Windows container support yet for these images. @pascalberger, are you asking for a Linux image?

**Comment by thechrisjohnson** [comment]
Yes, @stepro the TFS 2018 RTM versions can be found at https://github.com/Microsoft/vsts-agent/releases/tag/v2.122.1

**Comment by stepro** [comment]
Ok, I'll build a new set of (Linux) images for TFS 2018.

**Comment by stepro** [comment]
The images have been updated.
