### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by patrickfraley** [Microsoft/vsts-agent-docker#53]
Hi,
I am trying to get a docker vsts agent running and get the following error message:

```
>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html


>> Connect:

Connecting to server ...
An error occurred while sending the request.
```

The command I am using is:

```
docker run -it --name="agent-01" --network="bridge" -e TFS_HOST="TFSHOST" -e VSTS_TOKEN="STRENG_GEHEIM" -v /var/run/docker.sock:/var/run/docker.sock microsoft/vsts-agent:ubuntu-16.04-tfs-2017-docker-17.06.0-ce-standard
```
Of course the TOKEN in the command above is beeing replaced by a valid token and TFSHOST is beeing replaced by a resolveable hostname.

Things I have checked:

- The docker Server has access to the TFS Server (actually it itself had a agent running)
- I tried different immages (with and without docker)
- Tried different tokens by generating new ones

What am I doing wrong, what did I miss?

Thanks

**Comment by patrickfraley** [comment]
Ok I tried something new, by setting the, based on documention, optional env variables VSTS_POOL and VSTS_WORK in the command to the default values and now I get the following error message:

```
>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html


>> Connect:

Connecting to server ...
Basic authentication requires a secure connection to the server.
```

**Comment by stepro** [comment]
The best I can suggest here is to take a look at the container's startup script and compare how it is trying to run the agent to how you have successfully run the agent on the same node directly. The script is [here](https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/tfs/2017/docker/17.06.0-ce/standard/start.sh).

**Comment by patrickfraley** [comment]
Is there a switch, with which I can disable the security check that the basic auth would be allowed over http?  Since this is in our internal network that should not be a problem.

**Comment by stepro** [comment]
That would be a feature of the VSTS agent itself, and right now, I don't believe so. @chrisrpatterson, can you comment?

**Comment by patrickfraley** [comment]
Somehow it must work, since we have two agents running on windows machines, that do not seem to have this problem ...  I just don't know how they where started or installed.

**Comment by stepro** [comment]
Ah, ok. So there is a way with the agent. Can you look at what parameters are being passed to the agents running directly on the Windows machines? I think it's possible they are using Windows authentication to securely authenticate with the server which isn't possible from a Linux-based agent.

**Comment by stepro** [comment]
Closing stale issues.
