### ISSUE TITLE
Unhandled: Failed which: Not found docker: null

### ISSUE THREAD

**Issue by MherX** [Microsoft/vsts-agent-docker#56]
Hi all!
I ran almost all containers for VSTS but they all give the error below as I start the container and what error I get. 
Interestingly, when I connect to the container where the slit is.
I have Azure Container Registry can be the problem? it may be that you need to do? for example to authorize? 

Thank you advance!

docker run \
  -e VSTS_ACCOUNT=account\
  -e VSTS_TOKEN=token \
  -it microsoft/vsts-agent:ubuntu-16.04-docker-17.06.0-ce

Starting: Build an image for Bot
.........................................................................................................
Task         : Docker
Description  : Build, tag, push, or run Docker images, or run a Docker command. Task can be used with Docker or Azure Container registry.
Version      : 0.3.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
.........................................................................................................
Unhandled: Failed which: Not found docker: null
.........................................................................................................
Finishing: Build an image for Bot

**Comment by cameronattard** [comment]
You need to mount the host's Docker socket into the container:

`docker run \
  -e VSTS_ACCOUNT=<name> \
  -e VSTS_TOKEN=<pat> \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -it microsoft/vsts-agent:ubuntu-16.04-docker-17.06.0-ce`

**Comment by MherX** [comment]
Sorry! I just pointed out is not correct for the build agent the error is correct! 
But now he writes that Docker is not running!

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
/usr/local/bin/docker failed with return code: 1
