### ISSUE TITLE
What's wrong with vsts agent docker images?

### ISSUE THREAD

**Issue by alexsandro-xpt** [Microsoft/vsts-agent-docker#58]
Every month I am pull a image like `microsoft/vsts-agent:ubuntu-16.0x-docker-17.0x.0-ce-standard` image, but this month I get those erro, what's wrong?

![vsts agent error](https://user-images.githubusercontent.com/845657/34671022-e2670fb4-f45f-11e7-9307-a488305d26be.png)

**Comment by stepro** [comment]
This indicates an error in the response coming from VSTS when calling the endpoint that determines the correct version of the agent to install. Usually this is a result of your token being expired or otherwise invalid.

**Comment by alexsandro-xpt** [comment]
Thank you replay @stepro, that is it, I created another token and it's become work fine. I don't know way becouse another token isn't working, the expiration date still valid yet.

Well, I create another and everythink is working.. thanks!
