### ISSUE TITLE
Wrong Path to JAVA_HOME

### ISSUE THREAD

**Issue by TGippert** [Microsoft/vsts-agent-docker#6]
Hi, 

Java builds are not working for the image "microsoft/vsts-agent:ubuntu-16.04-docker-1.11.2-standard".
ERROR: 
```
JAVA_HOME is set to an invalid (not existing) directory: /usr/lib/jvm/default-java
Please set the JAVA_HOME variable in your environment to match the location of your Java installation.
```

**Reason:** 
Wrong ENV JAVA_HOME in DockerFile for image "microsoft/vsts-agent:ubuntu-16.04-docker-1.11.2-standard"
The correct path (working for me) to java is `/usr/lib/jvm/java-8-openjdk-amd64` instead of `/usr/lib/jvm/default-java`

**Workarounds:**
a) Set JAVA_HOME at docker run:
```
docker run \
  -e VSTS_ACCOUNT=<name> \
  -e VSTS_TOKEN=<token> \
  -e VSTS_POOL=<pool> \
  -e JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -it microsoft/vsts-agent:ubuntu-16.04-docker-1.11.2-standard
```

OR
b) Use an own Dockerfile
```
FROM microsoft/vsts-agent:ubuntu-16.04-docker-1.11.2-standard
# Fix issue with JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```

**Comment by stepro** [comment]
This issue has been fixed and the images have been updated.
