### ISSUE TITLE
vsts linux agent publish artifacts to windows share

### ISSUE THREAD

**Issue by aumanjoa** [Microsoft/vsts-agent-docker#62]
Hi,

using: https://github.com/Microsoft/vsts-agent-docker/tree/8d8873c218eb0055c4e0d5e94540a8b941c7e5e6/ubuntu/16.04/tfs/2017-u1/standard

I try to publish an artifact from an Linux agent () into an mounted smb foulder and get this error message: 

Cannot publish artifacts from OSX or Linux to a file share. You can change 'Artifact Type' to 'Server', use Windows, or use the 'Copy Files', 'Copy Files Over SSH', or 'FTP Upload' task.

The copy works fine but how I can use this files than after that in the release definition? I get the error there was nothing published

**Comment by stepro** [comment]
This sounds more like a question on the publish artifacts task, not the VSTS agent. Try asking the question at https://github.com/microsoft/vsts-tasks. It looks like it is not supported by the task.
