### ISSUE TITLE
[Docker] microsoft/vsts-agent - Queued build -> Missing capabilities: msbuild, visualstudio, DotNetFramework, vstest 

### ISSUE THREAD

**Issue by sietsevdschoot** [Microsoft/vsts-agent-docker#66]
When i start a docker agent, targeting visualstudio.com, the agent registers itself with my private agent pool. 
When i queue a new build, I get the following error:

> No registered agents found in the selected queue with the following capabilities: msbuild, visualstudio, DotNetFramework, vstest. Use a different queue.

```
docker run -e VSTS_ACCOUNT=[MyProject]-e TFS_HOST=[MyHost] -e VSTS_POOL=[MyPool] -e VSTS_TOKEN=[MyToken] -it microsoft/vsts-agent
```

Output:
```
Determining matching VSTS agent...
Downloading and installing VSTS agent...

>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2018-01-23 08:57:37Z: Settings Saved.
Scanning for tool capabilities.
Connecting to the server.
2018-01-23 08:57:39Z: Listening for Jobs
```
Googling this error, it appears VisualStudio is not installed on the image.

Any possible solutions on how to fix this in Docker?

**Comment by stepro** [comment]
If you want Windows only features like Visual Studio or the full .NET Framework, then you need to build and run your own Windows container using the resources available in this repository under the windows directory. The images that you can pull from Docker Hub are Linux only images.
