### ISSUE TITLE
NodeJS LTS version for docker image

### ISSUE THREAD

**Issue by Bene-Graham** [Microsoft/vsts-agent-docker#68]
Hello,

I noticed that the docker image is the the latest stable(currently Node 9), but the current LTS is Node 8.

This causes problem when using NPM to install package like bcrypt, where it is compiled to the specific node version.

I am wondering, shouldn't the docker image use the LTS version node since in most cases this is what the majority of people will use in production? 

If not, is there a way to work around this? The only solution I have found is to use NPM to remove and add on the actual production server after the deploy.

Regards,

**Comment by stepro** [comment]
I think it would be reasonable to change the version of Node installed to the LTS. I'll update the images.

**Comment by stepro** [comment]
The images have been updated.
