### ISSUE TITLE
Update docker-compose to latest version

### ISSUE THREAD

**Issue by stepro** [Microsoft/vsts-agent-docker#7]
This enables version 2.1 amongst other things.

**Comment by stepro** [comment]
Note: this should only be updated when the Docker engine is 1.12.0 or above.

**Comment by stepro** [comment]
I take that back - only when using version 2.1 of compose does it require Docker engine 1.12.0 or above. So it can still be used for version 2.0 against engine 1.11.2.

**Comment by saikatguha** [comment]
+1 to update docker-compose to latest version.

docker-compose 1.11.2 fixed a major performance bug where recursive wildcard patterns ** were not being recognized in .dockerignore files. This bug was often the culprit for invalidating docker cache.

**Comment by stepro** [comment]
The images have been updated.
