### ISSUE TITLE
Starting agent with invalid access token gives ambiguous error message

### ISSUE THREAD

**Issue by shantmarouti** [Microsoft/vsts-agent-docker#70]
## Agent version and platform
Docker 17.12.0-ce, build c97c6d6
ubuntu-16.04-docker-17.06.0-ce-standard#d7b6b317d640
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)

## VSTS type and version
VisualStudio.com

## What's not working?
When starting agent with invalid or expired access token it gives ambiguous error message:
```
Determining matching VSTS agent...
parse error: Invalid numeric literal at line 3, column 10
```
I think [this line](https://github.com/Microsoft/vsts-agent-docker/blob/8e19e2fdc98cb9a207522181a2e3eb46aff84f9d/ubuntu/start.sh#L57-L61) causes the error. Probably it receives invalid JSON from server.

## Agent and Worker's diag log
No log files exists

**Comment by stepro** [comment]
Yeah, this error could be handled better. @dakale, do you want to take look?

**Comment by dakale** [comment]
Sure, I can take a look at this
