### ISSUE TITLE
No maven, visualstudio or azureps capabilities found

### ISSUE THREAD

**Issue by maxklock** [Microsoft/vsts-agent-docker#8]
I'm running the vsts-agent with the command:

    docker run
        --name vsts-agent -d
        -e VSTS_ACCOUNT=<accont>
        -e VSTS_TOKEN=<token>
        -e VSTS_AGENT=vsts-agent-azure
        -e VSTS_POOL=Azure
        -it microsoft/vsts-agent:ubuntu-16.04-docker-1.12.1-standard

but when queue a new build, I'm getting the error, that there is no maven capabilitie. Even visualstudio or azureps is not found.

But the Docker description says, Java tools (ant, gradle, maven) and other capabilities should be installed

**Comment by stepro** [comment]
The current Docker images are based on Ubuntu Linux and as such can only run Linux workloads. This means that Visual Studio and Azure PS capabilities aren't expected to be available. However, maven is installed in the standard image but it must not be exposed properly. I will look into it.

**Comment by stepro** [comment]
Well the configuration between the hosted agent pool and this agent image is different. In the hosted agent pool, the "maven" capability points at the directory where maven is installed. In the custom agent, the "maven" capability points at the binary executable and also sets M2_HOME to point at the directory.

However, these differences shouldn't matter. The Maven task demands the "maven" capability and the custom agent does provide that. The code for the Maven task is [https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Maven/maventask.ts](here) and it looks like if the version selection is set to "Default", it will find the value of M2_HOME (/usr/share/maven) and append "bin/mvn". I verified that path does exist.

@maxklock, can you provide some more information on exactly the error you are getting around maven? How is your task configured?

**Comment by maxklock** [comment]
Task configuration:

    Maven pom.xml
        clean compile package
    Copy files to
        Source: $(build.sourcesdirectory)
        Target: $(build.artifactstagingdirectory)
    AzureBlob File Copy
        Source: $(build.artifactstagingdirectory)

The Agent in the Docker Image is started as "vsts-agent-azure" in pool "Azure"

Queue new build:

    Queue: Azure
    Branch: master

By clicking ok, I'm getting the following popup:

    There are issues with the request or definition that may prevent the build from running:
    No agent could be found with the following capabilities:
    maven, azureps
    Queue the build anyway?

By clicking no, it Abort, by clicking yes, I'm getting the following error:

    No agent found in pool Azure which satisfies the specified demands: maven, azureps 
    Agent.Version -gtVersion 1.103.0

**Comment by stepro** [comment]
According to the error message, it is looking for an agent with "maven" and "azureps" capabilities. The Maven task only demands "maven" so you must have another task that is demanding "azureps". Azure PowerShell is not available on Linux so this agent doesn't support that capability.
