### ISSUE TITLE
Request: Clang on VSTS Linux Agent

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/vsts-agent-docker#80]
The title says it all - would it be possible to have a recent version of Clang available on hosted Linux agents?  If I had a choice, I'd choose a version >= clang 5.0, but really any version that supports c++14 would work.

My concrete use case is that our project embeds https://github.com/Microsoft/ChakraCore, which requires clang to build on Linux.  I can certainly install it myself, but it would be a nice convenience to have it preinstalled, and would shave some time off of our builds.

Thanks!

**Comment by stepro** [comment]
Are you looking specifically for the hosted Linux agents to have this capability (@thechrisjohnson can comment) or for the hostable Linux container images to have this capability (this repo?) Or both?

**Comment by benjamin-bader** [comment]
I hadn't considered the distinction, but I'm interested in hosted Linux agents having this capability.  We aren't using the docker images directly.

**Comment by stepro** [comment]
Ok. I'd be happy to add it to the Docker images, but that won't affect the hosted Linux agents (I think they are based off the same images but there's an integration lag).

**Comment by benjamin-bader** [comment]
OK, thanks, that sounds great!  Do I understand correctly that this change would _eventually_ make it to the hosted agents?

**Comment by thechrisjohnson** [comment]
Yes, it's a pretty easy process to update the docker container on the hosted pools, there will just be a little delay as we take time waiting between releases to different Scale Units to ensure we don't break everybody at once.

**Comment by stepro** [comment]
The images have been updated.

**Comment by benjamin-bader** [comment]
Awesome, thank you all!
