### ISSUE TITLE
Update vsts agent for build YAML feature

### ISSUE THREAD

**Issue by mblaschke** [Microsoft/vsts-agent-docker#83]
When will the updated vsts agents be available? The current version doesn't support the "YAML - Configure your build as code" feature and if one developer triggers a YAML build all dockerized agents are updated and restarted.

I'm using a hosted VSTS on visualstudio.com and it tries to update the agent to 2.129.1 (dockerized version is 2.122.1). This update fails because it restarts the container and it comes up again with the agent version from the image.

**Comment by dakale** [comment]
There is a related issue open in https://github.com/Microsoft/vsts-agent-docker/issues/63 in which some workarounds are discussed that might be useful to you

You may need to pull the latest image- this issue has been at least partially mitigated by an update to the images (see issue linked above) 

Let me know if that is not enough information to work through your problem

**Comment by mblaschke** [comment]
I wasn't aware that the non-tfs-images are fetching the image on start which fixes our problem.

Thanks and closed :)
