### ISSUE TITLE
Unable to build Dockerfile that has apt-get update

### ISSUE THREAD

**Issue by cberthold** [microsoft/vsts-agent-docker#84]
I've been trying to figure out what needs to be done to make this image work on VSTS for a couple hours now.  original Dockerfile can be built from ```github.com/cberthold/kafka-pi```  on the `master` branch and also tried breaking the steps up on `testruns` branch.  This image builds fine and deploys on the Raspberry Pi and builds on the Mac (17.12) just fine.  

When running each command individually this is what I get:

Step 5/19 : COPY install.sh create-config-template.sh create-config-files.sh server-start.sh /tmp/
 ---> 051befdacf7b
Step 6/19 : RUN apt-get update
 ---> Running in 94edbb8aa40e
[91mstandard_init_linux.go:185: exec user process caused "exec format error"
[0mThe command '/bin/sh -c apt-get update' returned a non-zero code: 1
The command '/bin/sh -c apt-get update' returned a non-zero code: 1
/usr/local/bin/docker failed with return code: 1
******************************************************************************
Finishing: Build an image
******************************************************************************

Trying to put together a build and deployment pipeline around raspberry pis based microservices running .NET on Kubernetes.  Would be nice to get this part working.

**Comment by dakale** [comment]
I am unsure exactly what problem you are having as it relates to this repository. Are you trying to build your image on VSTS? If so, which agent queue are you using, or are you running your own agent? 

Are trying to build your image using either the Hosted Linux queue or you are running your own agent using one of these agent images?

**Comment by cberthold** [comment]
It was a suggestion from someone else to try here for ideas what might be causing the issue.  I'm building on VSTS hosted.  I've tried the linux and mac hosted.  My understanding is with the mac one I need to somehow install docker prior to executing the docker build.  My understanding as well is that the ARM portions of the build are shimmed into the container which is why it works on mac and pi at the same time.  I just do not know the difference between the Hosted Linux queue and Mac that does not allow this to build.  My alternative I would assume would be to run the VSTS build agent on the pi then?  Is that even possible at this point?  I realize I'm pushing the boundaries a bit, however, it's a cool one to push :)

**Comment by dakale** [comment]
Hi @cberthold sorry this fell off my radar. Have you been able to get your build working? 

If you havent moved on, I see no reason why you couldn't run the agent in a Docker container on the pi.
