### ISSUE TITLE
Docker Build Completes But Doesn't Work

### ISSUE THREAD

**Issue by pointtoken** [Microsoft/vsts-agent-docker#89]
We've been running our devops pipeline with VSTS docker builds for almost a year and something recently broke in the last few weeks and unfortunately we can't pinpoint what happened.

The VSTS Docker build step runs and then we push the image to an Azure container registry and run it as an app service. But it always throws an internal server error when trying to serve the website, which is an Angular universal app running using PM2. 

If we run the exact same Dockerfile on our local ubuntu box and push the image to the container registry, things work as expected.

Since the image is running alpine-node we can't see what is failing.

And if we download the docker image built by vsts, it fails on our local box. 

Sorry we don't have more diagnostics, but this is a big problem as we can no longer use vsts for our pipeline and have resorted to creating our builds local. 

This first appeared for us March 21, 2018. What changed around that time? Any suggestions?

**Comment by dakale** [comment]
Are you running your builds on the Hosted Linux Preview queue? Just to be clear, this repo is for the images that run on the machines backing the Hosted Linux queue, not the Docker tasks (build/push etc) in general.

Are you able to share the error from your server that you encountered? 

I am not aware of any major changes that would likely cause this, nor has anything similar been reported, so we are going to need to tease out some more information to narrow it down

When you say:
> And if we download the docker image built by vsts, it fails on our local box.

Do you mean the container exits with an error if you `docker run` it on your local machine vs running on App Service? You should be able to use `docker logs` to capture the logs of the container- maybe theres some information as to what the error is there

**Comment by pointtoken** [comment]
Thanks for the quick response and pointer to docker logs -- that revealed that the issue is in our code. Closing...
