### ISSUE TITLE
Add Ubuntu 17.10?

### ISSUE THREAD

**Issue by promgamer** [microsoft/vsts-agent-docker#95]
Hi,

Is there anything that prevent us from having a Ubuntu 17.10 version?

Cheers,

**Comment by dakale** [comment]
There is an additional support and maintenance burden for every new configuration that is added. Adding Ubuntu 17 without removing Ubuntu 14/16 would mean 50% more total linux images that need to be built and pushed which is already cumbersome. 

Unless there is a compelling need to upgrade, the existing images are stable and are all we plan to support at this time. Do you have a particular need for Ubuntu 17 that isnt satisfied by 14/16?

**Comment by promgamer** [comment]
It comes with some updated tooling like gcc 7 (and with that support for C++17). What I did right now was to pick a vsts_agent Docker image and install gcc 7 on it (although I don't really like to diverge from the "official" images).

Also, it would be nice to have conan installed (as it becomes more and more used).

**Comment by dakale** [comment]
In general we would be more likely to just support gcc 7 on the 14/16 images, so long as that package is available for those distributions. More so if gcc7 will be backwards compatible with whatever version is currently installed, or can be installed alongside older versions. 

Also just want to call out that we have added clang 6 to the 16 images. I'm not sure if that supports your use case but it's there if it does.

**Comment by iceb0y** [comment]
We have met a similar problem, where boost library has version 1.58 with ubuntu 16.04 lts. We would prefer debian 9 as build environment.
