### ISSUE TITLE
Reset Container after running job (i.e. Current Hosted Agent behavior)

### ISSUE THREAD

**Issue by iyerusad** [Microsoft/vsts-agent-docker#96]
Is there a particular reason that the docker containers don't reset after running a job like the Hosted Agents do? 

My expectation with the docker container is that it reset completely following job completion, which includes:
- Cleanup of files in working directory (this seems to work today)
- Environment is cleaned to container spec:
  - If I installed `tree` using apt-get, I expect that won't be installed on next run. As it currently stands, installing `tree` in a previous release, persists in next release which leads me to understand a dirty environment.

=========
1. Brand new Azure VM (Ubuntu 17.10), updated packages and installed Docker.

2. Running docker container as so:
```
sudo docker run \
  --name "$(hostname)-Agenttest" \
  --hostname "$(hostname)-Agenttest" \
  -e VSTS_ACCOUNT=myvstsaccount \
  -e VSTS_TOKEN=blahblah \
  -e VSTS_AGENT='$(hostname)' \
  -e VSTS_POOL="OnPrem Linux" \
  -e VSTS_WORK='/var/vsts/$VSTS_AGENT' \
  -v /var/vsts:/var/vsts \
  -it microsoft/vsts-agent
```

3. Trigger a Release that has a job for this VSTS pool. Job does its tasks.

4. Next Release/Job, expecting Agent to be reset to the default with no persistence from previous job. 

===========

Is there some sort of flag that needs to happen here to achieve parity with the Hosted (Linux) Agent behavior?

**Comment by dakale** [comment]
In the hosted (linux) queue, a separate service creates and managers the lifecycle of a container to run your job so you don't share a potentially modified environment with others. 

As far as I know, there is not currently an official way to support your ask. We are moving to model where this is possible but unfortunately that is still WIP. 

It is a bit awkward for a self-host container because VSTS would need to be able to tell your host machine when the build was complete, but there wont be such a service on your host. I quickly experimented with a build definition that had a final phase calling `docker  kill/restart` to kill the agent container, but if the agent get killed the build cant really finish.

**Comment by stepro** [comment]
On of the main reasons you choose to run your own Linux agent is actually so that you can avoid the limitation of hosted agents where they lose all the context between builds. A custom agent allows you to be more efficient with your builds by maintaining a custom environment with the tools you need. In the Docker container case, you can derive your own image from one of the base images and install "tree" or whatever other tools you need for your builds.

If the behavior of hosted agents is what you are looking for, then you probably want to be using the hosted agents instead of running your own agent.

**Comment by iyerusad** [comment]
In a team that practices DevOps, I can't ensure John doesn't introduce a dependency hell for Paul's pipelines and vice versa. So really, this logically is a bug with the VSTS docker container/really all the VSTS agents as they share modified environments with others. Agents shouldn't be "pets" but cattle. For some reason it was deemed proper to solve this for Hosted agents, but not for selfhosted agents (we do have multiple people working on projects folks).

Please consider reopening this request as it seems like a valid issue given nature of multiple member teams.

Blurb about our use case:
----
Our use case is we are looking to deploy Docker container in a private VNet that can talk to private servers hosted in onprem datacenters. Personally prefer endpoints to be in Azure, but still well in transition.

Re: Custom container - We are looking build on top of VSTS tooling and not fork. Sure, can run custom container with custom tools etc etc etc... but its loads more suitable to `apt-install myspecialpony` during a pipeline within a managed service offering. I'm not looking to fork VSTS repos/docker containers.

Retaining context between builds is really an anti-feature of pipelines and a problem-matic one for our teams. We work with team members thousands of miles away, pipelines would mysteriously break when an agent is reboot/recycled (experienced in other CI systems). A consistently clean environment is the first and foremost reason we use pipelines, it keeps the developers honest and builds consistent, everytime, everywhere, and **on every agent** (idempotent pipelines aside).

**Comment by stepro** [comment]
What you're asking for is not a request on the Docker containerization of the VSTS agent but the agent itself, so you'll be better off adding this feature request to the Microsoft/vsts-agent repository. @dakale can comment more, but I believe there are plans to move to a model where you have a single controlling VSTS agent which spins up an independent Docker container for each build, thus creating a lightweight isolated environment that is discarded after each build.

Until that is available, you could make use of the fact that Docker containers are lightweight to run and you could start up a number of different VSTS agents to be used by different members of your team, but all running on the same machine or set of machines. This isolates team member from each other , but you're not going to get idempotency.

**Comment by iyerusad** [comment]
I'll post it there, looking forward to the improved model @dakale .

but fwiw, I believe adding a monitor to the within docker container that looks for the "job completed" and does a docker kill/restart. This would be out of band of the job who called it (and won't stop the job being able to finish). May introduce a race condition though in registering the agent theoretically.

**Comment by stepro** [comment]
Yeah, that likely wouldn't work because it will end up constantly removing and re-adding agents in the agent pool, and it might end up missing jobs as a result.

**Comment by kirkone** [comment]
hi,

I know this is closed but I had the same problem and solved it by running my agents like so:

```
if [ "$TFS_AGENT_DISPOSE" = true ]; then
  env_include+=( "Agent.Private=true" )
  ( env ${env_exclude[@]/#/-u } "${env_include[@]}" ./bin/Agent.Listener run & echo $! ) | ( trap 'kill "$pid"' EXIT; pid="$(head -1)"; sed -e '/Job Build completed with result/q')
else
  env ${env_exclude[@]/#/-u } "${env_include[@]}" ./bin/Agent.Listener run & wait $!
fi
```

This is an example only but should give a hint on how to get something like that working.

**Comment by iyerusad** [comment]
Here is an updated version of that monstrosity that runs as a system service on the docker host:

**vstsdockermonitorservice.yml**
```
- name: Install VSTS Docker Monitor service
  hosts: all
  gather_facts: no

  tasks:
  - name: Get local user
    run_once: True
    set_fact:
      ansible_local_user: "{{ lookup('pipe', 'id -un') | d(lookup('pipe', 'whoami'), True) | d(lookup('env', 'USER'), True) |  d(lookup('env', 'user'), True) |  d(lookup('env', 'LOGNAME'), True) }}"
    failed_when: ansible_local_user == ''

  - name: Add local user to docker group
    user:
      name: "{{ansible_local_user}}"
      groups: docker
      append: yes
      state: present
    become: true

  - name: Instantiate VSTS Docker monitor script
    file:
      path: /usr/local/bin/vstsdockermonitor.sh
      state: touch
      owner: root
      group: root
      mode: 0664
    become: true
    changed_when: false

  - name: Inject content into VSTS docker monitor script
    copy:
      content: |
        {% raw %}#!/bin/bash
        runningarray=()
        
        while :
        do
        
          activecontainers=( $(docker container list --format="{{.Names}}") )
          
          #Adding any new containers to cleaner function
          for obj in "${activecontainers[@]}"; do
              if [[ ! " ${runningarray[@]} " =~ " ${obj} " ]]; then
                echo "Adding $obj to monitoring for cleanup"
                /usr/local/bin/vstsdockercleanup.sh "$obj" &
                runningarray+=("$obj")
              #else
                 #echo "$obj already monitored for cleaning"
              fi
          done
        
          #Rebuild array to only include existing containers
          temparray=()
          for obj in "${runningarray[@]}"; do
              if [[ ! "$(docker container list --format="{{.Names}}")" =~ "$obj" ]]; then
                echo "$obj no longer active, Killing vstsdockercleanup instance and removing $obj from cleaner array"
                kill $(ps aux | grep vstsdockercleanup.sh | grep "$obj" | awk '{ print $2 }') > /dev/null
              else
                #echo "$obj is still active, keeping in running array"
                temparray+=("$obj")
              fi
          done
          runningarray=("${temparray[@]}")
          unset temparray
        
          sleep 15
        done
        {% endraw %}
      dest: /usr/local/bin/vstsdockermonitor.sh
    become: true
    register: vstsmonitorscript

  - name: Instantiate VSTS docker clean up script
    file:
      path: /usr/local/bin/vstsdockercleanup.sh
      state: touch
      owner: root
      group: root
      mode: 0755
    become: true
    changed_when: false

  - name: Inject content into VSTS docker monitor script
    copy:
      content: |
        {% raw %}#!/bin/bash
        container="$1"
        
        while :
        do
          sleep 1
          msg=$(docker logs "$container" --tail 1)
          #echo "$container - $msg"
          if [[ "$msg" = *"completed"* ]]; then
            echo "$container - A job completed, Agent is now dirty!"
            echo "$container - Cleanup: checking if safe to clean agent"
        
            loops=0
            looptime=$((60*60)) #1hour
            matchcount=0
            count=0
        
            while [ $matchcount -lt 15 ] && [ $loops -lt $looptime ]
            do
              sleep 1
              latestmsg=$(docker logs "$container" --tail 1)
              #echo "$container - $latestmsg"
        
              if [ "$latestmsg" = "$msg" ] && [[ "$latestmsg" = *"completed"* ]]; then
                matchcount=$((matchcount + 1))
                echo "$container - Cleanup: Agent reporting idle, Counting off $matchcount of 15"
                count=$((count + 1))
              else
                matchcount=0 #If msg not match consecutively, reset matchcount to 0
                echo "$container - Cleanup: Agent still busy. Match count is reset to $matchcount"
                count=$((count + 1))
              fi
        
              if [ $count -gt 15 ] && [ $matchcount -lt 15 ]; then
                echo "$container - Cleanup: Agent still busy after last 15 checks,"
                echo "$container - Cleanup: Resetting msg and counter"
                msg=$(docker logs "$container" --tail 1)
                count=0
                matchcount=0
              fi
        
              loops=$((loops + 1))
            done
        
            if [ $loops -lt $looptime ]; then
              docker stop --time 20 "$container" > /dev/null #Gracefully shuts down container, allowing it to be unregistered from VSTS queue
              docker restart "$container" > /dev/null
              cleaned="yes"
            else #stdout error message after looptime exceeded
              echo "$container - Cleanup ERROR: Wasn't able to cleanup agent, restarting cleaning function, better luck next round? "
            fi
          fi
          
          if [[ "$msg" = *"Listening for Jobs"* ]] && [[ "$cleaned" = *"yes"* ]]; then
            echo "$container - $msg"
            cleaned="done"
          fi
        done
        {% endraw %}
      dest: /usr/local/bin/vstsdockercleanup.sh
    become: true
    register: vstsdockercleanup

  - name: Instantiate VSTS Docker Monitor systemd service file
    file:
      path: /etc/systemd/system/vstsdockermonitor.service
      state: touch
      owner: root
      group: root
      mode: 0664
    become: true
    changed_when: false

  - name: Inject content into VSTS Docker Monitor service file
    copy:
      content: |
        [Unit]
        Description=VSTS Container Cleanup Service
        After=network.target
        
        [Service]
        Type=simple
        User={{ansible_local_user}}
        WorkingDirectory=/usr/local/bin
        ExecStart=/bin/bash vstsdockermonitor.sh
        
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/vstsdockermonitor.service
    become: true
    register: vstsdockermonitorservice

  - name: Reload VSTS Docker Monitor service file
    shell: |
      systemctl daemon-reload
    #when: vstsdockermonitorservice.changed
    become: true

  - name: Stop VSTS Docker Monitor service (if needed)
    service:
      name: vstsdockermonitor.service
      state: stopped
    when: vstsdockermonitorservice.changed or vstsmonitorscript.changed or vstsdockercleanup.changed
    become: true

  - name: Start VSTS Docker Monitor service
    service:
      name: vstsdockermonitor.service
      state: started
      enabled: yes
    become: true
```

You can install it by calling the recipe against a host like so:
`ansible-playbook -i "12.34.567.891", vstsdockermonitorservice.yml`

Seems to work. ¯\_(ツ)_/¯
