### ISSUE TITLE
Option to run dockerized image behind proxy

### ISSUE THREAD

**Issue by ryanmendoza** [microsoft/vsts-agent-docker#99]
Is there a configuration to run this behind a proxy? It would be easy enough to create the `.proxy` file, but I'm not seeing a way to pass the proxy in the configuration command? 

Am I missing something?

**Comment by dakale** [comment]
When you `docker run` can you just pass `--env HTTP_PROXY "http://host:port"`? Im not completely sure but I think the networking is going to different when running in a container vs running directly on the host so passing the proxy config to the agent may not be necessary.

Alternatively if the agent needs the .proxy file you may be able to mount that in when you run the container

I dont think you are missing anything though. If you take a look at the `start.sh` file youll see how the agent is started up- no proxy settings are passed. If thats something that is required for your use case we can discuss potentially adding it

**Comment by ryanmendoza** [comment]
@dakale I think it would definitely be useful. Our corporate network is frequently riddled with proxy gotchas. This type of configuration makes sense to me to be available amongst the others as a docker run environment parameter.
